-- Update service content for all 14 active services
-- This migration updates taglines, short descriptions, service explainers,
-- workflow stages, whats included, service risks, profile personas, and FAQs

-- 1. Private Limited Company Registration
UPDATE service_packages SET
  tagline = 'Your company, incorporated. Separate legal entity, limited liability, ready for investment.',
  short_description = 'Incorporate your Private Limited Company with full MCA compliance - DSC, DIN, MOA/AOA, PAN, TAN included.',
  service_explainer = '{"steps":[{"step":1,"title":"What it is","visual":"info","body":"A Private Limited Company is a business entity registered under the Companies Act, 2013. It is a separate legal person - it can own property, enter contracts, hire employees, and sue or be sued in its own name. Shares are held by up to 200 shareholders and cannot be publicly traded."},{"step":2,"title":"Why you need it","visual":"sparkles","body":"If you plan to raise equity investment, Pvt Ltd is the only structure that works - investors receive shares, and an LLP cannot issue them. It also enables ESOPs for employees, gives you a clean cap table, and provides the credibility that enterprise clients and banks look for."},{"step":3,"title":"What happens without it","visual":"alert","body":"Without incorporation, you operate as a proprietorship with unlimited personal liability - creditors can go after your personal assets. You cannot raise equity, issue ESOPs, or provide the legal continuity that investors and acquirers require."}]}'::jsonb,
  workflow_stages = '[{"step":1,"title":"Answer 5 questions - we build your checklist","timeline":"Day 0","body":"Number of directors, shareholders, proposed company name (3 options recommended), registered office state, and authorised capital. A company secretary is assigned within 4 hours.","visual":"checklist","milestone":"CS assigned, checklist sent"},{"step":2,"title":"Upload documents through the app","timeline":"Day 0-2","body":"PAN and Aadhaar for all directors, address proof for the registered office, passport photos. Your CS verifies every document before filing - mismatches caught here, not after MCA raises a query.","visual":"upload","milestone":"Documents verified by CS"},{"step":3,"title":"DSC and DIN arranged for all directors","timeline":"Day 2-4","body":"Digital Signature Certificates and Director Identification Numbers are mandatory. We arrange DSC tokens and guide each director through video verification in the app.","visual":"form","milestone":"DSC and DIN ready"},{"step":4,"title":"Name approved via RUN","timeline":"Day 4-7","body":"Your CS files the Reserve Unique Name application with MCA. Approval typically takes 2-3 working days. If a name is rejected, we file alternatives immediately at no extra cost.","visual":"form","milestone":"Company name approved"},{"step":5,"title":"SPICe+ filed - MOA, AOA, PAN, TAN in one submission","timeline":"Day 7-12","body":"SPICe+ is the single integrated MCA form for incorporation, PAN, TAN, and optional GST pre-enrollment. Your CS drafts the MOA and AOA based on your specific business activities and files with the Registrar of Companies.","visual":"form","milestone":"SPICe+ submitted to MCA"},{"step":6,"title":"Certificate of Incorporation issued","timeline":"Day 12-15","body":"MCA issues your CIN. PAN and TAN are generated automatically. All documents are uploaded to your Ollvy account permanently. Your compliance calendar is populated with every annual deadline.","visual":"stamp","milestone":"Company incorporated","isCompletion":true}]'::jsonb,
  whats_included = '[{"title":"DSC for all directors - video verification guided","body":"Digital Signature Certificates are mandatory. We arrange the tokens and guide each director through video verification. Takes 15 minutes per director.","comparisonWithout":"Navigate DSC portals yourself - 3+ hours","comparisonWithOllvy":"Guided flow in app - 15 minutes per director"},{"title":"DIN as part of SPICe+ - no separate filing","body":"Director Identification Number is included in SPICe+. No separate DIR-3 application, no extra time.","comparisonWithout":"Separate DIR-3 filing - adds 3-5 days","comparisonWithOllvy":"DIN filed simultaneously in SPICe+"},{"title":"MOA and AOA drafted for your business","body":"Main objects, ancillary objects, and authorised capital are drafted based on what you actually do - not a generic template that needs amendment later.","comparisonWithout":"Generic template - may need amendment later","comparisonWithOllvy":"Custom drafting based on your business activities"},{"title":"PAN and TAN included","body":"SPICe+ includes both applications. Issued within 24 hours of CIN with no separate process."},{"title":"Compliance calendar auto-populated","body":"From the day your company is incorporated, your calendar shows every deadline: first board meeting (30 days), ADT-1 auditor appointment (15 days from AGM), DIR-3 KYC (Sep 30 every year), MCA annual filing, and Business ITR."},{"title":"All documents stored permanently","body":"Certificate of Incorporation, MOA, AOA, PAN, TAN, share certificates, and DSC details - all in your Ollvy account. Your CA will ask for these repeatedly over the years."}]'::jsonb,
  service_risks = '[{"icon":"document","title":"Name rejected by MCA","body":"MCA rejects names similar to existing companies or those containing restricted words (Bank, Insurance, Exchange, etc.). We search MCA and trademark databases before submitting. If all 3 names are rejected, we suggest alternatives at no extra cost."},{"icon":"mismatch","title":"Registered address document mismatch","body":"The address on your utility bill must match your application exactly. If using a rented address, you need NOC from the landlord. Your CS verifies all address documents before filing."},{"icon":"clock","title":"Director slow on DSC video verification","body":"SPICe+ cannot be filed until all directors complete DSC verification. Ollvy sends daily reminders and tracks completion status. The verification itself takes 10-15 minutes per director."}]'::jsonb,
  profile_personas = '[{"label":"First-time founder","detail":"Never incorporated before. We explain every document and step before you take it."},{"label":"Solo director","detail":"Single-director company. MOA drafted to reflect full operational authority."},{"label":"Two co-founders in different cities","detail":"DSC video verification done remotely. Common situation, handled."},{"label":"Home address as registered office","detail":"Fully legal. We verify address proof requirements before filing."},{"label":"Raising investment soon","detail":"Authorised capital set appropriately. Board composition planned for investor entry."}]'::jsonb,
  faqs = '[{"category":"General","q":"How long does incorporation take?","a":"15 working days end-to-end. DSC takes 2 days, name approval 3 days, SPICe+ filing and MCA approval 10 days. MCA processing speed is outside our control, but we file the moment documents are ready."},{"category":"General","q":"What is the minimum capital required?","a":"No legal minimum. Authorised capital can be Rs 1 lakh (the standard starting point). Stamp duty on incorporation is based on authorised capital and varies by state."},{"category":"General","q":"Pvt Ltd or LLP - which should I choose?","a":"Pvt Ltd if you plan to raise equity, issue ESOPs, or need the company structure for credibility with enterprise clients. LLP if you are a professional services firm or want simpler compliance and profit-sharing. See our full comparison guide."},{"category":"Process","q":"Can I be the only director?","a":"A Pvt Ltd requires a minimum of 2 directors and 2 shareholders. For single-person ownership, consider OPC (One Person Company)."},{"category":"Process","q":"What if my proposed name is rejected?","a":"We search MCA and trademark databases before filing to minimise rejection risk. If rejected, we refile alternatives immediately at no extra cost."},{"category":"Documents","q":"What documents do directors need?","a":"PAN card, Aadhaar card, passport photo, mobile number linked to Aadhaar for OTP, and address proof. Directors must complete video verification for DSC."},{"category":"After Completion","q":"What are my compliance obligations after incorporation?","a":"File Form INC-20A (commencement of business declaration) within 180 days - this requires the initial share capital to be deposited in a company bank account, so open a current account immediately. Annual obligations: MCA annual return (AOC-4 due 30 days after AGM, MGT-7 due 60 days after AGM), Director KYC by Sep 30, Business ITR by Oct 31. All added to your compliance calendar automatically."},{"category":"After Completion","q":"Does this include GST registration?","a":"No. GST registration is a separate service. Mandatory once your turnover crosses the threshold. You can book both together - both CAs are assigned the same day."}]'::jsonb
WHERE slug = 'pvt-ltd-incorporation';

-- 2. LLP Incorporation
UPDATE service_packages SET
  tagline = 'Limited liability. Flexible profit-sharing. Lower compliance than Pvt Ltd.',
  short_description = 'Register your Limited Liability Partnership with MCA. DPIN, DSC, LLP Agreement, and PAN included.',
  service_explainer = '{"steps":[{"step":1,"title":"What it is","visual":"info","body":"A Limited Liability Partnership is registered under the LLP Act, 2008. It combines partnership flexibility with limited liability - partners are not personally liable for business debts beyond their agreed contribution. Unlike a Pvt Ltd, there are no shares, no board meetings, and no mandatory audit below the turnover threshold."},{"step":2,"title":"Why you need it","visual":"sparkles","body":"LLP is the right structure if you are a professional services firm, want direct management involvement without board formalities, or need flexible profit-sharing that does not follow capital contribution. Annual compliance costs are significantly lower than a Pvt Ltd."},{"step":3,"title":"What happens without it","visual":"alert","body":"Operating as an unregistered partnership means unlimited personal liability for all partners. One partner''s actions can put other partners'' personal assets at risk. The firm cannot own property in its name or enforce contracts in court."}]}'::jsonb,
  workflow_stages = '[{"step":1,"title":"Answer questions - we build your checklist","timeline":"Day 0","body":"Business type, number of partners, proposed LLP name (3 options), registered state, capital contribution split. A company secretary is assigned within 4 hours.","visual":"checklist","milestone":"CS assigned, checklist sent"},{"step":2,"title":"Upload documents through the app","timeline":"Day 0-1","body":"PAN and Aadhaar for all partners, registered address proof, capital contribution details. CS verifies every document before filing.","visual":"upload","milestone":"Documents verified by CS"},{"step":3,"title":"DPIN and DSC arranged","timeline":"Day 1-3","body":"Designated Partner Identification Number is required for all partners. We file applications and arrange DSC tokens with guided video verification.","visual":"form","milestone":"DPIN and DSC ready"},{"step":4,"title":"FiLLiP filed - LLP Agreement, PAN in one submission","timeline":"Day 4-9","body":"FiLLiP is the integrated LLP incorporation form. Your CS drafts the LLP Agreement based on your actual partner arrangement and files with MCA.","visual":"form","milestone":"FiLLiP submitted to MCA"},{"step":5,"title":"LLPIN issued","timeline":"Day 10-12","body":"MCA issues the Certificate of Incorporation with your LLP Identification Number. PAN is generated automatically. All documents uploaded to your account.","visual":"stamp","milestone":"Certificate of Incorporation issued","isCompletion":true}]'::jsonb,
  whats_included = '[{"title":"LLP Agreement drafted - not templated","body":"The agreement defines profit-sharing, decision-making, capital contribution, and exit terms. Drafted based on your actual arrangement - not a generic 50-50 template.","comparisonWithout":"Generic template - disputes arise later","comparisonWithOllvy":"Custom agreement reflecting your actual split and roles"},{"title":"DPIN for all designated partners","body":"Every designated partner needs a DPIN. We file all applications simultaneously."},{"title":"DSC arranged - video verification guided","body":"DSC required for all partners. We arrange tokens and guide video verification in the app."},{"title":"Compliance calendar auto-populated","body":"Once LLPIN is issued, your calendar shows Form 11 (annual return, due May 30) and Form 8 (statement of accounts, due Oct 30)."}]'::jsonb,
  service_risks = '[{"icon":"document","title":"Name similarity rejection","body":"LLP names must be distinct from existing LLPs and companies. We check both registries before submission."},{"icon":"alert","title":"LLP Agreement must reflect actual terms","body":"Vague profit-sharing or unclear exit clauses are the most common source of partner disputes. We draft explicit percentages and terms."},{"icon":"clock","title":"All partners must complete DSC verification","body":"FiLLiP cannot be filed until every partner completes video verification. We send daily reminders."}]'::jsonb,
  profile_personas = '[{"label":"Professional services firm","detail":"CA firms, law firms, architects, consultants - LLP is the natural fit."},{"label":"Two equal partners","detail":"50-50 split. Agreement drafted to handle deadlock scenarios."},{"label":"Three partners, unequal contribution","detail":"Different capital, different profit share. We draft it exactly."},{"label":"Converting from partnership","detail":"Existing firm converting to LLP. We handle the transition."}]'::jsonb,
  faqs = '[{"category":"General","q":"LLP vs Pvt Ltd - which should I choose?","a":"LLP if you are a professional services firm, do not plan to raise equity investment, and want lower compliance costs. Pvt Ltd if you plan to raise funding, issue ESOPs, or need share-based ownership structure. See our full comparison guide."},{"category":"General","q":"Can I convert an LLP to Pvt Ltd later?","a":"Yes, under Section 366 of the Companies Act, 2013. It involves multiple MCA filings, stamp duty, and a valuation exercise - typically 3-6 months. If funding is even a possibility in the next 3 years, start as Pvt Ltd."},{"category":"Process","q":"How many partners are required?","a":"Minimum 2 designated partners. No maximum. At least 2 must be Indian residents."},{"category":"Process","q":"Does an LLP need to hold board meetings?","a":"No. LLPs have no requirement for formal board or general meetings. Partners decide as agreed in the LLP Agreement."},{"category":"Documents","q":"What documents do partners need?","a":"PAN card, Aadhaar card, address proof. For the LLP: registered office address proof."},{"category":"After Completion","q":"What are the annual compliance requirements?","a":"Form 11 (Annual Return) by May 30 every year. Form 8 (Statement of Accounts and Solvency) by October 30 every year. ITR-5 by July 31 if no tax audit is required, or October 31 if tax audit applies (turnover above Rs 1 crore). No mandatory statutory audit below Rs 40 lakh turnover and Rs 25 lakh contribution."}]'::jsonb
WHERE slug = 'llp-incorporation';

-- 3. GST Registration
UPDATE service_packages SET
  tagline = 'Your GSTIN, applied for and obtained. We handle every step.',
  short_description = 'Get your GSTIN within 7 working days. CA assigned same day, ARN shared within 24 hours of filing.',
  service_explainer = '{"steps":[{"step":1,"title":"What it is","visual":"info","body":"GST registration gives you a 15-digit GSTIN under the CGST Act, 2017. It authorises you to collect GST from customers, claim Input Tax Credit on purchases, and file GST returns."},{"step":2,"title":"Why you need it","visual":"sparkles","body":"Mandatory if your turnover exceeds Rs 40 lakh (Rs 20 lakh for services, Rs 10 lakh in special category states), for any inter-state supply, or if you sell on any e-commerce platform. Even below the threshold, being registered lets your B2B clients claim ITC on your invoices - without it, you are harder to work with than a registered competitor."},{"step":3,"title":"What happens without it","visual":"alert","body":"Operating without mandatory registration is tax evasion. Penalty is 100% of tax due plus Rs 10,000 minimum. You cannot claim ITC on your own purchases, cannot generate e-way bills, and platforms like Amazon and Flipkart will not onboard you."}]}'::jsonb,
  workflow_stages = '[{"step":1,"title":"Answer 5 questions - we build your checklist","timeline":"Day 0","body":"Business type, state, turnover estimate, supply type (goods/services/both), and whether you need voluntary registration. CA assigned within 4 hours. They generate a specific document checklist - not the standard 20-item government list.","visual":"checklist","milestone":"CA assigned, personalised checklist sent"},{"step":2,"title":"Upload documents through the app","timeline":"Day 0-1","body":"Upload directly from your phone. CA reviews every document before filing - blurry Aadhaar, address mismatch, wrong format - caught here, not after the officer raises a query.","visual":"upload","milestone":"Documents verified by CA"},{"step":3,"title":"Application filed - ARN in 24 hours","timeline":"Day 1-2","body":"CA files GST REG-01 on the GSTN portal. Application Reference Number generated immediately on submission and shared in your app the same day. You can verify status yourself at gstn.gov.in.","visual":"form","milestone":"ARN generated and sent to your app"},{"step":4,"title":"Officer query handled (if applicable)","timeline":"Day 3-5","body":"GST officers request clarifications in approximately 20% of cases, typically for Aadhaar verification or address proof. Your CA responds within 24 hours. Included in scope - no extra charge.","visual":"form","milestone":"Query responded"},{"step":5,"title":"GSTIN issued","timeline":"Day 5-7","body":"Permanent - no renewal, no expiry as long as you file returns. Compliance calendar updated automatically with your first GSTR-1 (11th of next month) and GSTR-3B (20th of next month) due dates.","visual":"stamp","milestone":"GSTIN active on GSTN portal","isCompletion":true}]'::jsonb,
  whats_included = '[{"title":"CA handles the GSTN portal - all 23 fields","body":"GST REG-01 has 23 fields across 5 tabs. Your CA completes the entire form. You answer 5 questions in the app.","comparisonWithout":"23 fields, 5 tabs, 3-4 hours on government portal","comparisonWithOllvy":"5 questions, approximately 4 minutes"},{"title":"ARN shared same day - track it yourself","body":"ARN is generated on submission and shared immediately. You can verify status on the GSTN portal yourself - you do not have to take our word for it."},{"title":"Officer queries handled - no extra charge","body":"If the GST officer requests clarification, your CA responds within 24 hours. Part of the service."},{"title":"Compliance calendar updated automatically","body":"GSTR-1 and GSTR-3B due dates appear in your calendar the moment GSTIN is issued. Nothing to set up manually."}]'::jsonb,
  service_risks = '[{"icon":"mismatch","title":"Address proof mismatch","body":"The business address on all documents must match exactly - building name, floor, area, and PIN code. Your CA checks every document for consistency before filing."},{"icon":"alert","title":"Aadhaar OTP fails","body":"GST registration requires Aadhaar-based authentication. If the mobile linked to Aadhaar is old or inactive, OTP fails. This must be fixed at an Aadhaar enrolment centre. We verify this upfront."},{"icon":"clock","title":"Already past threshold","body":"If your turnover has crossed the mandatory limit and you are not yet registered, you are liable for 100% of unpaid tax plus Rs 10,000 minimum penalty. Registering now stops the liability from growing."}]'::jsonb,
  profile_personas = '[{"label":"First GST registration","detail":"Never done this before. We explain what each document is for and why it is needed."},{"label":"Turnover just crossed threshold","detail":"You waited until legally required. Now we register you quickly."},{"label":"Voluntary registration","detail":"Below threshold but want to issue GST invoices to B2B clients. Completely legal."},{"label":"Home as principal place of business","detail":"Fully legal. We verify your electricity bill matches before filing."}]'::jsonb,
  faqs = '[{"category":"General","q":"When is GST registration mandatory?","a":"When aggregate turnover crosses Rs 40 lakh (Rs 20 lakh for service providers, Rs 10 lakh for special category states). Also mandatory for any inter-state supply regardless of turnover, and for all e-commerce sellers from day one."},{"category":"General","q":"Can I register voluntarily if I am below the threshold?","a":"Yes. Voluntary registration lets you issue GST invoices and claim ITC on purchases. Cannot be cancelled for at least one year from date of registration."},{"category":"Process","q":"What is an ARN and why does it matter?","a":"Application Reference Number - generated the moment your application is submitted. You can track status on the government portal yourself without waiting for updates from us."},{"category":"Process","q":"What if the officer raises a query?","a":"Your CA responds within 24 hours. Included in the service. Most queries are resolved in one reply."},{"category":"Documents","q":"What documents do I need?","a":"Depends on your business type. Sole proprietor: PAN, Aadhaar, address proof, bank statement. Pvt Ltd: same, plus Certificate of Incorporation, board resolution, and director PANs. We send a personalised checklist."},{"category":"After Completion","q":"What are my obligations after getting GSTIN?","a":"GSTR-1 by 11th of every month (outward supplies), GSTR-3B by 20th (net tax payment). Nil returns required even if there are no transactions. GSTR-9 annual return by December 31. All deadlines added to your compliance calendar automatically."}]'::jsonb
WHERE slug = 'gst-registration';

-- 4. GST Monthly Filing
UPDATE service_packages SET
  tagline = 'GSTR-1 by the 11th. GSTR-3B by the 20th. Every month. Handled.',
  short_description = 'Monthly GST return filing - GSTR-1 and GSTR-3B filed on time, with ITC reconciliation each cycle.',
  service_explainer = '{"steps":[{"step":1,"title":"What it is","visual":"info","body":"Monthly GST compliance means filing GSTR-1 (outward supplies, due 11th) and GSTR-3B (net tax payment, due 20th) every month. GSTR-1 reports every sales invoice. GSTR-3B calculates your tax liability, deducts eligible Input Tax Credit, and records your payment to the government."},{"step":2,"title":"Why you need it","visual":"sparkles","body":"All regular GST-registered taxpayers must file monthly - including nil returns when there are no transactions. Consecutive missed filings trigger e-way bill suspension, then registration suspension, then suo-moto cancellation. Your customers also cannot claim ITC on your invoices until you file."},{"step":3,"title":"What happens without it","visual":"alert","body":"Late filing fee of Rs 50 per day per return (Rs 20 for nil returns), capped at Rs 10,000 per return. Interest at 18% per annum on unpaid tax. E-way bill generation blocked after two consecutive missed filings. Registration cancelled after 6 months of non-filing."}]}'::jsonb,
  workflow_stages = '[{"step":1,"title":"Share your GST credentials","timeline":"Day 0","body":"Read-only access to your GST portal. CA reviews your filing history and is assigned to your account permanently.","visual":"checklist","milestone":"CA assigned to your account"},{"step":2,"title":"Upload sales invoices and purchase data","timeline":"By 8th of each month","body":"Sales invoices and purchase register. If you use Tally, Zoho, or any accounting software, an export takes 2 minutes.","visual":"upload","milestone":"Data received for the month"},{"step":3,"title":"GSTR-1 filed by the 11th","timeline":"9th-11th","body":"CA files all outward supply invoices. Acknowledgement shared in your app.","visual":"form","milestone":"GSTR-1 filed"},{"step":4,"title":"GSTR-3B filed by the 20th","timeline":"18th-20th","body":"CA prepares the summary return, verifies ITC claims against GSTR-2B, calculates net tax liability, and files. Challan generated.","visual":"form","milestone":"GSTR-3B filed"},{"step":5,"title":"Monthly compliance report","timeline":"21st-25th","body":"What was filed, when, acknowledgement numbers, ITC claimed, tax paid.","visual":"checklist","milestone":"Report delivered","isCompletion":true}]'::jsonb,
  whats_included = '[{"title":"GSTR-1 - outward supply return","body":"All B2B invoices, B2C sales above Rs 2.5 lakh, and export invoices reported. Filed by the 11th."},{"title":"GSTR-3B - net tax payment","body":"Output tax calculated, eligible ITC deducted, return filed, challan generated."},{"title":"ITC reconciliation with GSTR-2B","body":"ITC claimed is matched against GSTR-2B before filing. Mismatches flagged - you are not exposed to a notice for claiming ITC your vendor has not filed.","comparisonWithout":"Claim ITC without verification, receive a demand notice later","comparisonWithOllvy":"ITC verified against GSTR-2B every cycle before filing"},{"title":"Monthly compliance report","body":"Filed returns, acknowledgement numbers, ITC summary, and tax paid - delivered after every cycle."}]'::jsonb,
  service_risks = '[{"icon":"clock","title":"Late fee accumulates quickly","body":"Rs 50 per day per return, Rs 100 per day for both returns combined. Plus 18% interest on any unpaid tax. Penalties are avoidable - data must be shared by the 8th."},{"icon":"mismatch","title":"GSTR-1 and GSTR-3B figures must match","body":"Discrepancies between the two returns are flagged automatically by GSTN. We file both from the same data set to ensure consistency."},{"icon":"alert","title":"Vendor not filed = ITC blocked","body":"If your vendor has not filed their GSTR-1, their invoices do not appear in your GSTR-2B. Claiming ITC on those invoices invites a mismatch notice. We check before claiming."}]'::jsonb,
  profile_personas = '[{"label":"Switching from another CA","detail":"Seamless takeover. We review your filing history before the first cycle."},{"label":"Multiple GSTINs","detail":"Multiple states, multiple registrations. All handled under one retainer."},{"label":"High transaction volume","detail":"500+ invoices a month. Priced by turnover, not invoice count."},{"label":"Previous CA stopped responding","detail":"We work to SLA every month. You get acknowledgement numbers, not silence."}]'::jsonb,
  faqs = '[{"category":"General","q":"What does the monthly retainer cover?","a":"GSTR-1 by 11th, GSTR-3B by 20th, ITC reconciliation against GSTR-2B, and monthly compliance report."},{"category":"General","q":"Can I cancel anytime?","a":"Yes. No minimum term. Cancel before the 1st of any month and you will not be charged for that cycle."},{"category":"Process","q":"What data do I need to share each month?","a":"Sales invoices and purchase register. If you use accounting software, the export takes 2 minutes."},{"category":"Process","q":"What if I have no transactions in a month?","a":"Nil GSTR-1 and GSTR-3B must still be filed. We handle nil returns as part of the retainer."}]'::jsonb
WHERE slug = 'gst-monthly';

-- 5. Business ITR Filing
UPDATE service_packages SET
  tagline = 'ITR-6 for Pvt Ltd. ITR-5 for LLP. Filed correctly, on time.',
  short_description = 'Annual income tax return filing for companies and LLPs. Includes depreciation review, computation, and draft approval before filing.',
  service_explainer = '{"steps":[{"step":1,"title":"What it is","visual":"info","body":"Business ITR is the annual income tax return filed by companies (ITR-6) and LLPs or partnerships (ITR-5) under Section 139 of the Income Tax Act, 1961. It reports income, expenses, depreciation, and tax computation for the financial year and is due October 31 for tax audit cases."},{"step":2,"title":"Why you need it","visual":"sparkles","body":"Mandatory for every company and LLP regardless of whether the business made a profit or loss. Filing a loss return preserves your right to carry it forward against future profits. Banks, visa offices, and government tender departments ask for 2-3 years of ITR as standard."},{"step":3,"title":"What happens without it","visual":"alert","body":"Interest at 1% per month on unpaid tax from the due date. Loss returns filed late cannot carry forward losses - that tax benefit is permanently gone. The department can reopen assessments up to 3 years back for unexplained discrepancies."}]}'::jsonb,
  workflow_stages = '[{"step":1,"title":"Upload your financials","timeline":"Day 0-1","body":"P&L, Balance Sheet, trial balance, bank statements. CA assigned within 4 hours.","visual":"upload","milestone":"Documents received, CA assigned"},{"step":2,"title":"CA reviews books and prepares computation","timeline":"Day 1-4","body":"CA reviews P&L, verifies depreciation schedule, checks director remuneration treatment, and prepares income computation.","visual":"form","milestone":"Draft computation ready"},{"step":3,"title":"You review and approve the draft","timeline":"Day 4-7","body":"Complete draft ITR shared in the app - income figures, deductions, tax computation. You review and approve before anything is filed.","visual":"checklist","milestone":"Draft approved"},{"step":4,"title":"Filed and acknowledgement delivered","timeline":"Day 7-10","body":"CA files within 24 hours of approval. ITR-V acknowledgement generated immediately and shared in the app same day.","visual":"stamp","milestone":"ITR-V acknowledgement delivered","isCompletion":true}]'::jsonb,
  whats_included = '[{"title":"Depreciation review","body":"CA reviews your asset schedule and depreciation rates. Incorrect rates - under or over - are flagged before filing."},{"title":"Director remuneration treatment","body":"For Pvt Ltd companies, how director salary is treated versus dividends has tax implications. CA reviews compliance with Companies Act limits."},{"title":"Full draft review before filing","body":"You see the complete return before it is filed - income, deductions, tax computation. Nothing is filed without your explicit approval."},{"title":"ITR-V stored permanently","body":"Acknowledgement uploaded to your Ollvy account immediately. Available whenever you need it - for loan applications, visa, or audits."}]'::jsonb,
  service_risks = '[{"icon":"clock","title":"Belated filing interest","body":"Section 234A: if you file after the due date with tax outstanding, 1% monthly interest accrues from the original deadline."},{"icon":"document","title":"Losses cannot be carried forward if filed late","body":"A company that made a loss and files after October 31 loses the right to offset that loss against future profits. That tax benefit cannot be recovered."},{"icon":"alert","title":"Audit requirement","body":"Audit is mandatory if turnover exceeds Rs 1 crore (Rs 10 crore if cash transactions are under 5% of total). Audited financials must be ready before ITR can be filed."}]'::jsonb,
  profile_personas = '[{"label":"First year after incorporation","detail":"First ITR. We walk through every document required."},{"label":"Changed CA mid-year","detail":"Previous CA''s books need reconciliation. We clean up and file correctly."},{"label":"Company made a loss","detail":"Loss return filed to preserve carry-forward rights."},{"label":"Filing late","detail":"We calculate interest liability upfront so there are no surprises, then file immediately."}]'::jsonb,
  faqs = '[{"category":"General","q":"When is Business ITR due?","a":"For Pvt Ltd companies: October 31 - statutory audit is mandatory for all companies regardless of turnover, so the extended deadline always applies. For LLPs not requiring tax audit: July 31. For LLPs requiring tax audit (turnover above Rs 1 crore): October 31."},{"category":"General","q":"What is the difference between ITR-5 and ITR-6?","a":"ITR-6 for companies (Pvt Ltd, Public Ltd, OPC). ITR-5 for LLPs and partnership firms."},{"category":"Process","q":"What documents do I need?","a":"Audited financials (P&L, Balance Sheet), trial balance, bank statements, Form 26AS, and depreciation schedule."},{"category":"Process","q":"Do I need a statutory audit?","a":"Mandatory for all Pvt Ltd companies regardless of turnover. For LLPs: mandatory above Rs 40 lakh turnover or Rs 25 lakh contribution."}]'::jsonb
WHERE slug = 'business-itr';

-- 6. Trademark Registration
UPDATE service_packages SET
  tagline = 'Protect your brand name. 10-year protection. Nationwide.',
  short_description = 'Trademark application filed within 7 days. Includes search, class guidance, and examiner objection response.',
  service_explainer = '{"steps":[{"step":1,"title":"What it is","visual":"info","body":"Trademark registration gives you exclusive rights to use your brand name, logo, or tagline for a specific category of goods or services across India for 10 years (renewable indefinitely). Registered under the Trade Marks Act, 1999, it lets you use the R symbol and take legal action against infringers."},{"step":2,"title":"Why you need it","visual":"sparkles","body":"Without registration, you have limited legal recourse against anyone using your brand name. Someone else can register it before you and force you to rebrand. E-commerce platforms require trademark registration for brand protection features. Investors and acquirers treat registered IP as a tangible asset."},{"step":3,"title":"What happens without it","visual":"alert","body":"Proving passing off without a registered trademark is expensive and uncertain. You have no access to Amazon Brand Registry or similar platform protections. Anyone can legally use a similar name in your category."}]}'::jsonb,
  workflow_stages = '[{"step":1,"title":"Tell us your brand name and category","timeline":"Day 0","body":"Trademark attorney assigned within 4 hours. You provide the mark (word, logo, or both), the classes you want to protect, and your business details. Preliminary search started immediately.","visual":"checklist","milestone":"Attorney assigned, search started"},{"step":2,"title":"Trademark search report delivered","timeline":"Day 1-2","body":"Attorney searches the Trademark Registry for identical and similar marks in your classes. Search report shows potential conflicts. If your mark is clear, we proceed. If not, we suggest modifications.","visual":"form","milestone":"Search report delivered"},{"step":3,"title":"Application filed with Trademark Registry","timeline":"Day 3-7","body":"Attorney drafts the application, selects the correct class(es), prepares the trademark specification, and files. You receive your application number and filing receipt.","visual":"form","milestone":"Application filed, receipt received"},{"step":4,"title":"Examination and publication","timeline":"6-12 months (government processing)","body":"The Trademark Registry examines your application. If objections are raised, your attorney responds - included in scope. Once cleared, the mark is published in the Trademark Journal for 4 months.","visual":"calendar","milestone":"Under examination"},{"step":5,"title":"Registration certificate issued","timeline":"12-18 months total","body":"Certificate issued. Your mark is protected for 10 years from the filing date, renewable indefinitely. Certificate stored in your Ollvy account.","visual":"stamp","milestone":"Trademark registered","isCompletion":true}]'::jsonb,
  whats_included = '[{"title":"Trademark search before filing","body":"Attorney searches the Registry before we spend your government fee. If your exact mark is already registered in your class, we tell you upfront.","comparisonWithout":"File without searching, wait months, get rejected","comparisonWithOllvy":"Search first, modify if needed, then file"},{"title":"Class selection guidance","body":"Trademarks are registered per class (45 classes under the Nice Classification). Attorney recommends only the classes you actually need - we do not push unnecessary filings."},{"title":"Examiner objection response included","body":"If the Trademark Examiner raises objections (common for descriptive marks), your attorney responds. Included in the service - not a separate charge.","comparisonWithout":"Objection raised, you pay extra to respond","comparisonWithOllvy":"Objection response included in service"},{"title":"Renewal reminder","body":"Trademark expires 10 years from filing date. Renewal reminder added to your compliance calendar 6 months before expiry."}]'::jsonb,
  service_risks = '[{"icon":"document","title":"Similar mark already exists","body":"If a similar mark is already registered in your class, the Examiner will reject your application. Our search catches most conflicts, but pending applications that are not yet published cannot be seen. If rejected, we help you appeal or modify."},{"icon":"clock","title":"Government processing takes 12-18 months","body":"The 7-day timeline is for filing. Examination, publication, and certificate issuance are government-side. We track and update you but cannot speed up the Registry."},{"icon":"alert","title":"Opposition during publication","body":"After examination, your mark is published for 4 months. Anyone can file an opposition. If opposed, it becomes a formal legal proceeding. Opposition response is a separate service and is rare - happens in under 5% of cases."}]'::jsonb,
  profile_personas = '[{"label":"First trademark","detail":"Never registered before. We explain classes, search, and the full process."},{"label":"Logo and word mark","detail":"You want to protect both. Two separate applications needed. We handle both."},{"label":"Multiple classes","detail":"Tech, retail, and services. Each class is a separate application and a separate government fee."},{"label":"Already using the name","detail":"You have been using the brand for years without registration. File now before someone else does."}]'::jsonb,
  faqs = '[{"category":"General","q":"What can I trademark?","a":"Words, logos, slogans, sounds, and in some cases colours. Most businesses file a word mark and a logo mark separately for broader protection."},{"category":"General","q":"How long does protection last?","a":"10 years from the filing date, renewable indefinitely in 10-year increments."},{"category":"Process","q":"Why does registration take 12-18 months?","a":"The 7-day timeline is for filing. Examination by the Registry takes 6-12 months. Then 4 months of public opposition window. Then certificate issuance. All government-side processing."},{"category":"Process","q":"Can I use the R symbol after filing?","a":"No. Use R only after registration is granted. Until then, use TM (for goods) or SM (for services) to indicate your claim."},{"category":"Documents","q":"What documents do I need?","a":"PAN, Aadhaar, address proof, and the logo file if registering a logo. For companies: Certificate of Incorporation and board resolution."},{"category":"Pricing","q":"What if I need multiple classes?","a":"Each class is a separate application with a separate government fee. Our attorney will recommend only the classes you actually need."}]'::jsonb
WHERE slug = 'trademark-registration';

-- 7. MCA Annual Filing
UPDATE service_packages SET
  tagline = 'AOC-4 and MGT-7. The annual return every Pvt Ltd must file.',
  short_description = 'Annual ROC compliance for Pvt Ltd - AOC-4 (financial statements) and MGT-7 (annual return) filed together.',
  service_explainer = '{"steps":[{"step":1,"title":"What it is","visual":"info","body":"MCA Annual Filing for a Private Limited Company consists of two mandatory ROC forms: AOC-4 (audited financial statements) and MGT-7 (annual return reporting shareholding, directors, and meeting details). Both are filed with the Registrar of Companies every year."},{"step":2,"title":"Why you need it","visual":"sparkles","body":"Mandatory for every Pvt Ltd regardless of whether the company was active. AOC-4 is due within 30 days of the AGM. MGT-7 is due within 60 days of the AGM. The AGM must be held within 6 months of the financial year end (by September 30 for companies with March year-end). Non-filing results in company status being marked as Default on MCA - visible to anyone doing due diligence."},{"step":3,"title":"What happens without it","visual":"alert","body":"Penalty of Rs 100 per day per form with no ceiling. Both forms outstanding means Rs 200 per day. Directors can be disqualified under Section 164(2) if filing defaults persist. Banks may flag accounts on seeing Default status. Company can be struck off as defunct after 2 years of non-filing."}]}'::jsonb,
  workflow_stages = '[{"step":1,"title":"Share company details","timeline":"Day 0","body":"Company CIN, financial year, AGM date, and status of audited financials. CS assigned.","visual":"checklist","milestone":"CS assigned"},{"step":2,"title":"Upload financial statements and documents","timeline":"Day 0-2","body":"Audited Balance Sheet, P&L, director report, auditor report, and shareholder list. CS reviews before drafting forms.","visual":"upload","milestone":"Documents reviewed"},{"step":3,"title":"Forms drafted and sent for approval","timeline":"Day 2-4","body":"AOC-4 and MGT-7 drafted. You review and approve in the app.","visual":"form","milestone":"Draft forms approved"},{"step":4,"title":"Filed on MCA21 - SRN generated","timeline":"Day 5-7","body":"Both forms filed. Service Request Numbers shared immediately as proof of filing.","visual":"stamp","milestone":"AOC-4 and MGT-7 filed","isCompletion":true}]'::jsonb,
  whats_included = '[{"title":"Both forms filed - AOC-4 and MGT-7","body":"AOC-4 for financial statements, MGT-7 for annual return. Both included in scope."},{"title":"Deadline calculation based on your AGM","body":"AOC-4 due 30 days after AGM. MGT-7 due 60 days after AGM. We track both dates from the AGM date you provide."},{"title":"Penalty calculation if filing late","body":"If filing after the deadline, we calculate the exact penalty amount upfront before filing. No surprises."},{"title":"SRN shared immediately","body":"Service Request Number is your proof of filing. Both SRNs shared the day forms are submitted."}]'::jsonb,
  service_risks = '[{"icon":"document","title":"Audit must be complete first","body":"AOC-4 requires signed, audited financial statements. We cannot file until the audit is done. Plan your audit timeline to allow filing before the deadline."},{"icon":"clock","title":"AGM not held on time","body":"If your AGM is delayed past September 30, MCA filing deadlines shift. We calculate new deadlines from your actual AGM date."},{"icon":"alert","title":"Penalty accrues daily","body":"Rs 100 per day per form from the deadline. For both forms, Rs 200 per day. No ceiling on the penalty. File as soon as documents are ready."}]'::jsonb,
  profile_personas = '[{"label":"First year after incorporation","detail":"First MCA filing. We explain every field and what it means."},{"label":"Running past the deadline","detail":"Already in default. We calculate penalty and file immediately to stop it."},{"label":"Director changes during the year","detail":"Appointments and resignations reflected correctly in MGT-7."},{"label":"Share transfer happened","detail":"Updated shareholding pattern captured accurately."}]'::jsonb,
  faqs = '[{"category":"General","q":"When is MCA annual filing due?","a":"AOC-4: within 30 days of AGM. MGT-7: within 60 days of AGM. AGM must be held by September 30 for companies with a March financial year end."},{"category":"General","q":"Is this different from Business ITR?","a":"Yes. MCA annual filing is for the Ministry of Corporate Affairs (company registry). Business ITR is filed with the Income Tax department. Both are mandatory and have separate deadlines."},{"category":"Process","q":"Can I file if the audit is not complete?","a":"No. AOC-4 requires signed, audited financials."},{"category":"Process","q":"What if I missed the deadline?","a":"Penalty is Rs 100 per day per form from the due date. We calculate the exact amount and file immediately to stop further accumulation."},{"category":"Documents","q":"What documents do I need?","a":"Audited Balance Sheet, P&L, notes to accounts, director report, auditor report, and updated shareholder list."}]'::jsonb
WHERE slug = 'mca-annual-filing';

-- 8. TDS Monthly Compliance
UPDATE service_packages SET
  tagline = 'Deduct TDS. Deposit the challan. File the return. Every month, on time.',
  short_description = 'Monthly TDS calculation, challan preparation, and quarterly return filing for all payment types.',
  service_explainer = '{"steps":[{"step":1,"title":"What it is","visual":"info","body":"TDS compliance means withholding tax from payments you make to vendors, contractors, employees, and landlords, depositing it with the government by the 7th of the following month, and filing quarterly returns (Form 24Q for salary, Form 26Q for non-salary). It is a separate obligation from your own tax liability."},{"step":2,"title":"Why you need it","visual":"sparkles","body":"Any business making payments above TDS thresholds for rent, professional fees, contractor payments, salary, or interest must deduct and deposit TDS. Failure to deduct means the entire expense can be disallowed - you effectively get taxed twice on it."},{"step":3,"title":"What happens without it","visual":"alert","body":"Interest at 1.5% per month on late deposit. Penalty up to Rs 200 per day for late filing of returns. If TDS is not deducted, the expense is disallowed under Section 40(a)(ia) - you pay tax on income you never actually kept. Vendors and employees cannot claim TDS credit in their own returns."}]}'::jsonb,
  workflow_stages = '[{"step":1,"title":"Share your payment register","timeline":"Day 1-5 of month","body":"Salary, vendor, rent, and contractor payments for the month. CA reviews applicable TDS rates for each category.","visual":"upload","milestone":"Data received"},{"step":2,"title":"TDS calculated and challans prepared","timeline":"Day 5-6","body":"CA calculates TDS for each payment category. Challans prepared with correct BSR codes and assessment year.","visual":"form","milestone":"Challans ready"},{"step":3,"title":"You pay the challans","timeline":"Day 6-7","body":"You transfer through net banking. CIN (Challan Identification Number) uploaded to your account as proof.","visual":"stamp","milestone":"TDS deposited by 7th"},{"step":4,"title":"Quarterly return filed","timeline":"Quarter end","body":"CA files Form 24Q (salary TDS) and Form 26Q (non-salary TDS). Form 16 and 16A generation enabled after filing.","visual":"form","milestone":"TDS return filed","isCompletion":true}]'::jsonb,
  whats_included = '[{"title":"TDS calculation for all payment types","body":"Salary (192), contractor payments (194C), professional fees (194J), rent (194I), interest (194A). Correct rates applied to each."},{"title":"Challan preparation with correct codes","body":"Challan requires BSR code, assessment year, and correct minor head. Errors cause mismatches in the deductee''s Form 26AS. We prepare - you pay."},{"title":"Quarterly return filing","body":"Form 24Q for salary TDS, Form 26Q for all other deductions. Returns reconciled with challans before filing."},{"title":"Form 16/16A generation","body":"Once returns are filed, Form 16 (salary) and Form 16A (non-salary) can be downloaded from TRACES for your deductees."}]'::jsonb,
  service_risks = '[{"icon":"clock","title":"Deposit due by 7th - not the 31st","body":"TDS must be deposited by the 7th of the following month (March TDS by April 30). Late deposit incurs 1.5% per month interest from the date of deduction."},{"icon":"document","title":"Wrong TDS rate","body":"Under-deducting makes you liable for the shortfall plus interest. We apply current applicable rates for each section."},{"icon":"alert","title":"Missing PAN of deductees","body":"TDS at the higher rate of 20% applies if the deductee''s PAN is not furnished. We flag missing PANs during data review."}]'::jsonb,
  profile_personas = '[{"label":"First time deducting TDS","detail":"New to TDS obligations. We explain each section and threshold."},{"label":"Paying employees","detail":"Form 24Q salary TDS handled, Form 16 generated quarterly."},{"label":"Paying contractors or consultants","detail":"Form 26Q for 194C and 194J payments."},{"label":"Multiple payment types","detail":"Rent, salary, contractors, professional fees - all categories covered under one retainer."}]'::jsonb,
  faqs = '[{"category":"General","q":"Who needs to deduct TDS?","a":"Any business making payments above prescribed threshold limits - salary, rent above Rs 2.4 lakh per year, contractor payments above Rs 30,000 per contract or Rs 1 lakh per year, professional fees above Rs 30,000 per year."},{"category":"General","q":"What happens if I do not deduct TDS?","a":"The expense is disallowed under Section 40(a)(ia) - you pay tax on it as if it were profit. Plus interest at 1.5% per month on the amount that should have been deducted."},{"category":"Process","q":"When must TDS be deposited?","a":"By the 7th of the following month for most payments. For March, the deadline is April 30."},{"category":"Process","q":"When are TDS returns due?","a":"Quarterly. Q1 (April-June): July 31. Q2 (July-Sep): October 31. Q3 (Oct-Dec): January 31. Q4 (Jan-Mar): May 31."}]'::jsonb
WHERE slug = 'tds-monthly-compliance';

-- 9. MSME/Udyam Registration
UPDATE service_packages SET
  tagline = 'Government recognition. Priority lending. Payment protection.',
  short_description = 'Udyam registration certificate in 2 working days. Unlocks priority sector lending, 45-day payment protection, and government procurement preference.',
  service_explainer = '{"steps":[{"step":1,"title":"What it is","visual":"info","body":"Udyam Registration is free online registration with the Ministry of MSME. Based on your investment in plant and machinery, and annual turnover, you are classified as Micro, Small, or Medium Enterprise. You receive a Udyam Registration Number that identifies your MSME status for all government schemes."},{"step":2,"title":"Why you need it","visual":"sparkles","body":"To access any MSME benefit - priority sector bank loans, government procurement preference, or state subsidies - Udyam Registration is mandatory. Buyers above a certain size are legally required to pay MSME vendors within 45 days (the MSME Facilitation Council enforces this)."},{"step":3,"title":"What happens without it","visual":"alert","body":"You miss priority sector lending with lower interest rates. Large buyers can delay payment indefinitely without legal consequence. No access to government procurement reservations (25% of central government procurement is reserved for MSMEs). State incentives that require MSME status are unavailable."}]}'::jsonb,
  workflow_stages = '[{"step":1,"title":"Share Aadhaar and PAN","timeline":"Day 0","body":"Owner Aadhaar for OTP verification, business PAN. That is all that is needed.","visual":"checklist","milestone":"Details received"},{"step":2,"title":"Application filed on Udyam portal","timeline":"Day 1","body":"Filed on the official government portal with your investment and turnover details.","visual":"form","milestone":"Application submitted"},{"step":3,"title":"Udyam certificate issued","timeline":"Day 1-2","body":"Certificate with Unique Registration Number generated. GST linked automatically.","visual":"stamp","milestone":"MSME registered","isCompletion":true}]'::jsonb,
  whats_included = '[{"title":"Udyam certificate with URN","body":"Official certificate with Unique Registration Number - recognised by all banks, government departments, and e-marketplace platforms."},{"title":"Automatic GST linking","body":"Your GSTIN is linked to your Udyam registration at the time of application."},{"title":"Classification confirmed","body":"Micro, Small, or Medium status confirmed based on your investment and turnover. Classification determines which schemes apply to you."}]'::jsonb,
  service_risks = '[{"icon":"document","title":"Self-declaration based","body":"Investment and turnover figures are self-declared. Keep supporting records in case of verification."},{"icon":"alert","title":"Renewal not required but update needed","body":"Udyam registration does not expire, but if your turnover or investment changes your classification, the registration should be updated."}]'::jsonb,
  profile_personas = '[{"label":"Small business under Rs 5Cr investment","detail":"Manufacturing or services. Micro or Small classification."},{"label":"IT or consulting firm","detail":"Service enterprise. Investment threshold based on equipment, not premises."},{"label":"Applying for a bank loan","detail":"Bank requires Udyam certificate for priority sector loan classification."},{"label":"GeM seller","detail":"Government e-marketplace requires Udyam registration for MSME seller benefits."}]'::jsonb,
  faqs = '[{"category":"General","q":"What are the main benefits of MSME registration?","a":"Priority sector bank lending (lower interest rates), 45-day payment protection from large buyers, 25% reservation in central government procurement, state subsidies, and patent/ISO certification reimbursements."},{"category":"General","q":"Is Udyam registration free?","a":"Registration on the government portal is free. Our fee covers the filing assistance."},{"category":"Process","q":"How long is the certificate valid?","a":"Udyam registration does not expire. Update it if your investment or turnover changes your classification."},{"category":"Process","q":"Who qualifies as MSME?","a":"As of April 1, 2025 (revised in Union Budget 2025): Micro - investment up to Rs 2.5 crore and turnover up to Rs 10 crore. Small - investment up to Rs 25 crore and turnover up to Rs 100 crore. Medium - investment up to Rs 125 crore and turnover up to Rs 500 crore. A composite criterion applies - crossing either the investment or turnover limit for your current category moves you to the next category."}]'::jsonb
WHERE slug = 'msme-registration';

-- 10. GST Cancellation
UPDATE service_packages SET
  tagline = 'Close your GST registration properly. Final return filed.',
  short_description = 'GST registration cancellation with GSTR-10 (final return) and ITC reversal handled.',
  service_explainer = '{"steps":[{"step":1,"title":"What it is","visual":"info","body":"GST cancellation is the formal process of surrendering your GSTIN when you close your business or your turnover drops below the mandatory threshold. It involves filing REG-16 (cancellation application) and GSTR-10 (final return declaring closing stock and reversing ITC)."},{"step":2,"title":"Why you need it","visual":"sparkles","body":"If you stop business or fall below the threshold, continuing to hold a GSTIN means continuing to file monthly returns - even nil ones. Missed returns on an inactive registration trigger penalties and eventually suo-moto cancellation, which is harder to resolve than a clean voluntary cancellation."},{"step":3,"title":"What happens without it","visual":"alert","body":"Monthly returns continue to be mandatory. Each missed return is Rs 50 per day per return. After 6 months of non-filing, the department cancels your registration suo-moto - at which point you owe all pending returns, interest, and penalties before you can do anything."}]}'::jsonb,
  workflow_stages = '[{"step":1,"title":"ITC and liability review","timeline":"Day 0-2","body":"Remaining ITC balance and pending tax liabilities reviewed. ITC on closing stock must be reversed.","visual":"checklist","milestone":"Liability position confirmed"},{"step":2,"title":"GSTR-10 prepared","timeline":"Day 2-5","body":"Final return prepared with closing stock details and ITC reversal calculation.","visual":"form","milestone":"Final return ready"},{"step":3,"title":"REG-16 and GSTR-10 filed","timeline":"Day 5-10","body":"Cancellation application and final return filed simultaneously.","visual":"form","milestone":"Cancellation filed"},{"step":4,"title":"Cancellation order received","timeline":"Day 10-15","body":"GST officer reviews and issues the cancellation order.","visual":"stamp","milestone":"GST registration cancelled","isCompletion":true}]'::jsonb,
  whats_included = '[{"title":"Final return GSTR-10","body":"Closing stock details, ITC reversal calculation, and final return prepared and filed."},{"title":"REG-16 filing","body":"Cancellation application with reason and supporting details."},{"title":"ITC reversal handled","body":"Remaining ITC on closing stock reversed correctly - prevents demand notices after cancellation."}]'::jsonb,
  service_risks = '[{"icon":"alert","title":"ITC reversal is mandatory","body":"Any ITC taken on goods still in stock at the time of cancellation must be reversed or paid back. This is calculated before filing."},{"icon":"document","title":"Pending returns must be cleared first","body":"All outstanding GSTR-1 and GSTR-3B returns must be filed before a cancellation application can be processed."}]'::jsonb,
  profile_personas = '[{"label":"Closing business","detail":"Winding down operations. Full clean-up handled."},{"label":"Below threshold","detail":"Turnover dropped below Rs 40 lakh and you no longer need to be registered."},{"label":"Switching to composition scheme","detail":"Cancelling regular registration before registering as composition dealer."}]'::jsonb,
  faqs = '[{"category":"General","q":"What happens to my remaining ITC balance?","a":"ITC on closing stock must be reversed and paid back to the government. We calculate this before filing."},{"category":"General","q":"Can I re-register for GST later?","a":"Yes. A fresh registration application can be filed if your turnover crosses the threshold again."},{"category":"Process","q":"How long does cancellation take?","a":"15 working days from application to cancellation order, assuming no pending returns or outstanding liabilities."},{"category":"Process","q":"What if I have pending returns?","a":"All pending GSTR-1 and GSTR-3B must be filed before we can file the cancellation application. We file those first."}]'::jsonb
WHERE slug = 'gst-cancellation';

-- 11. GST Revocation
UPDATE service_packages SET
  tagline = 'GST cancelled by the department? We restore it.',
  short_description = 'Revoke a suo-moto GST cancellation - pending returns filed, REG-21 submitted, registration restored.',
  service_explainer = '{"steps":[{"step":1,"title":"What it is","visual":"info","body":"GST revocation is the process of restoring a GSTIN that was cancelled suo-moto by the GST department - typically for non-filing of returns for 6 or more consecutive months. It involves filing all pending returns, paying interest, and submitting REG-21 (revocation application) within 30 days of the cancellation order."},{"step":2,"title":"Why you need it","visual":"sparkles","body":"A cancelled GSTIN means you cannot issue GST invoices, claim ITC, or generate e-way bills. If you want to continue business, revocation is the only path - you cannot simply re-register if cancelled for non-compliance."},{"step":3,"title":"What happens without it","visual":"alert","body":"Business operations requiring GST invoicing are blocked. Clients cannot claim ITC on any invoices raised after cancellation. The 30-day window to apply for revocation closes. After that, reinstatement requires an appeal to the appellate authority, which is more complex."}]}'::jsonb,
  workflow_stages = '[{"step":1,"title":"Review cancellation order","timeline":"Day 0-1","body":"Reason and date of suo-moto cancellation confirmed. Outstanding returns identified.","visual":"checklist","milestone":"Cancellation order reviewed"},{"step":2,"title":"File all pending returns","timeline":"Day 1-5","body":"All outstanding GSTR-1 and GSTR-3B filed with interest on late payment.","visual":"form","milestone":"Pending returns cleared"},{"step":3,"title":"REG-21 filed","timeline":"Day 5-7","body":"Revocation application submitted with explanation.","visual":"form","milestone":"Revocation application filed"},{"step":4,"title":"GST registration restored","timeline":"Day 7-10","body":"Officer reviews and restores registration.","visual":"stamp","milestone":"GSTIN active","isCompletion":true}]'::jsonb,
  whats_included = '[{"title":"All pending returns filed","body":"Every outstanding GSTR-1 and GSTR-3B cleared before revocation application. Interest on late payment calculated and paid."},{"title":"REG-21 application","body":"Revocation request with explanation of the default and confirmation that returns are now current."},{"title":"Interest calculation","body":"Exact interest liability on late-deposited tax calculated before filing so you know the total amount upfront."}]'::jsonb,
  service_risks = '[{"icon":"clock","title":"30-day deadline","body":"Revocation must be applied for within 30 days of the cancellation order date. Extensions are possible but require a separate application. Act immediately on receiving a cancellation order."},{"icon":"alert","title":"All pending returns must be filed first","body":"The department will not process REG-21 unless all outstanding returns are filed and taxes paid with interest."}]'::jsonb,
  profile_personas = '[{"label":"Missed filings for several months","detail":"GST cancelled for non-filing. All returns cleared and registration restored."},{"label":"Need to continue invoicing clients","detail":"GSTIN required for ongoing business. We treat this as urgent."}]'::jsonb,
  faqs = '[{"category":"General","q":"Why was my GST cancelled?","a":"Suo-moto cancellation is typically triggered after 6 or more consecutive months of non-filing."},{"category":"General","q":"What is the time limit for applying for revocation?","a":"30 days from the date of the cancellation order. Apply immediately - do not wait."},{"category":"Process","q":"Can I re-register if revocation fails?","a":"If the revocation window is missed, you must file an appeal with the Appellate Authority. This is a more involved process. Acting within 30 days avoids this."}]'::jsonb
WHERE slug = 'gst-revocation';

-- 12. DIN Reactivation
UPDATE service_packages SET
  tagline = 'DIN deactivated? We restore it.',
  short_description = 'Reactivate a deactivated Director Identification Number - pending KYC filed, DIR-3C application submitted, DIN restored.',
  service_explainer = '{"steps":[{"step":1,"title":"What it is","visual":"info","body":"DIN Reactivation is the process of restoring a Director Identification Number that has been deactivated - most commonly for non-filing of the annual DIR-3 KYC by September 30. It involves filing all outstanding DIR-3 KYC forms, paying the late fee, and submitting a DIR-3C reactivation application."},{"step":2,"title":"Why you need it","visual":"sparkles","body":"A deactivated DIN means you cannot sign any company filings, resolutions, or official documents. Every company where you are a director is blocked from filing any MCA form until your DIN is restored. The penalty for each missed DIR-3 KYC is Rs 5,000."},{"step":3,"title":"What happens without it","visual":"alert","body":"All companies where you hold a directorship cannot file their annual returns, director changes, or any other MCA form. If this persists, those companies accumulate penalties and can be marked as Default on MCA."}]}'::jsonb,
  workflow_stages = '[{"step":1,"title":"Check reason for deactivation","timeline":"Day 0-1","body":"DIN status verified on MCA21. Years of outstanding KYC identified.","visual":"checklist","milestone":"Deactivation reason confirmed"},{"step":2,"title":"File all pending DIR-3 KYC","timeline":"Day 1-5","body":"DIR-3 KYC filed for all outstanding years with OTP verification. Rs 5,000 late fee applies per missed year.","visual":"form","milestone":"All KYC filings cleared"},{"step":3,"title":"DIR-3C reactivation application","timeline":"Day 5-7","body":"Reactivation form filed with explanation and payment.","visual":"form","milestone":"Reactivation application submitted"},{"step":4,"title":"DIN reactivated","timeline":"Day 7-10","body":"DIN status changed to Active on MCA21.","visual":"stamp","milestone":"DIN active, all directorships restored","isCompletion":true}]'::jsonb,
  whats_included = '[{"title":"All outstanding DIR-3 KYC filed","body":"Every year of missed KYC cleared. OTP verification coordinated in real time."},{"title":"DIR-3C application","body":"Reactivation form with explanation submitted to MCA."},{"title":"DIN fully restored","body":"All directorial rights, signing authority, and MCA filing access restored across all companies."}]'::jsonb,
  service_risks = '[{"icon":"clock","title":"Rs 5,000 per missed year","body":"The government late fee is Rs 5,000 per year of missed DIR-3 KYC. Multiple missed years means multiple fees - these are mandatory and non-negotiable."},{"icon":"building","title":"All companies blocked until DIN is active","body":"Every company where you are a director cannot file any MCA form while your DIN is deactivated. The impact is not limited to one company."}]'::jsonb,
  profile_personas = '[{"label":"Missed DIR-3 KYC","detail":"DIN deactivated for one or more years of missed KYC. Act before the company''s filing deadlines pass."},{"label":"Multiple directorships","detail":"One DIN reactivation covers all companies. We verify all directorships are unblocked."}]'::jsonb,
  faqs = '[{"category":"General","q":"Why was my DIN deactivated?","a":"Deactivated when DIR-3 KYC is not filed by September 30 each year. Automated by MCA from October 1."},{"category":"General","q":"What is the late fee?","a":"Rs 5,000 per year of missed DIR-3 KYC. This is a government fee and is fixed."},{"category":"Process","q":"How long does reactivation take?","a":"10 working days from when we receive your documents."},{"category":"Process","q":"Does reactivation fix the issue for all companies where I am a director?","a":"Yes. Your DIN is a single identifier. Reactivating it restores your status across all directorships."}]'::jsonb
WHERE slug = 'din-reactivation';

-- 13. Company Name Change
UPDATE service_packages SET
  tagline = 'New name. Same company. All MCA formalities handled.',
  short_description = 'Company name change with MCA - name availability search, special resolution, RUN filing, INC-24, and new Certificate of Incorporation.',
  service_explainer = '{"steps":[{"step":1,"title":"What it is","visual":"info","body":"A company name change under Section 13 of the Companies Act, 2013 involves passing a special resolution of shareholders, reserving the new name via RUN, amending the Memorandum of Association, and filing INC-24 with MCA. MCA issues a new Certificate of Incorporation with the updated name."},{"step":2,"title":"Why you need it","visual":"sparkles","body":"If you are rebranding, pivoting your business model, or resolving a conflict with another company''s name, the legal name change must be completed through MCA. Using a new trading name without changing the registered name creates legal and commercial inconsistencies."},{"step":3,"title":"What happens without it","visual":"alert","body":"Operating under a name different from your MCA-registered name creates confusion in contracts, invoices, and bank records. Counterparties doing due diligence will find the mismatch. Bank accounts, GST, and other registrations remain in the old name until formally updated."}]}'::jsonb,
  workflow_stages = '[{"step":1,"title":"Name availability check","timeline":"Day 0-2","body":"New name searched against MCA company registry and trademark database. Conflicts identified before any filing.","visual":"checklist","milestone":"Name confirmed available"},{"step":2,"title":"Board and shareholder resolution","timeline":"Day 2-7","body":"Special resolution of shareholders required for name change. Board resolution and EGM notice drafted.","visual":"form","milestone":"Special resolution passed"},{"step":3,"title":"RUN filed","timeline":"Day 7-12","body":"Reserve Unique Name application submitted to MCA.","visual":"form","milestone":"New name reserved"},{"step":4,"title":"INC-24 filed with MOA amendment","timeline":"Day 12-18","body":"Name change application filed along with amended Memorandum of Association.","visual":"form","milestone":"INC-24 submitted"},{"step":5,"title":"New Certificate of Incorporation issued","timeline":"Day 18-20","body":"Fresh Certificate with new company name. CIN remains the same.","visual":"stamp","milestone":"Name change complete","isCompletion":true}]'::jsonb,
  whats_included = '[{"title":"Name availability search","body":"MCA company registry and trademark database both checked before filing to avoid rejection."},{"title":"Special resolution drafting","body":"Shareholder special resolution, board resolution, and EGM notice drafted per Companies Act requirements."},{"title":"MOA amendment","body":"Memorandum of Association updated to reflect the new name."},{"title":"New Certificate of Incorporation","body":"Fresh certificate issued by MCA with the new name. Your CIN, PAN, and TAN remain unchanged."}]'::jsonb,
  service_risks = '[{"icon":"alert","title":"Update all downstream registrations","body":"After the name change, you must update GST (core amendment), bank accounts, trademark if registered, import-export code, FSSAI if applicable, and all contracts. The MCA name change does not cascade automatically to other registrations."},{"icon":"document","title":"Trademark conflict","body":"If someone has registered a similar trademark, MCA may reject the name or you may receive a legal notice after the change. Our trademark search reduces this risk."}]'::jsonb,
  profile_personas = '[{"label":"Rebranding","detail":"New brand identity. MCA name aligned with new brand."},{"label":"Business pivot","detail":"Core business changed. Name no longer reflects the company."},{"label":"Name conflict","detail":"Another company has a similar name causing confusion. Changing to a distinct name."}]'::jsonb,
  faqs = '[{"category":"Process","q":"Does my PAN or GST change when I change my company name?","a":"PAN and TAN remain the same. GST requires a core amendment (name change update) - separate process but straightforward."},{"category":"Process","q":"Can I change the name to anything?","a":"Subject to MCA availability and not containing restricted words. Name must be distinct from existing companies and trademarks."},{"category":"Process","q":"How long does the process take?","a":"20 working days from start to new Certificate of Incorporation."},{"category":"Process","q":"Do I need a special resolution?","a":"Yes. A name change requires a special resolution (75% majority of shareholders voting in favour)."}]'::jsonb
WHERE slug = 'company-name-change';

-- 14. Cloud Kitchen Setup
UPDATE service_packages SET
  tagline = 'Every licence a cloud kitchen needs. One package. Done right.',
  short_description = 'Complete licensing for delivery-only food operations - FSSAI State License, GST Registration, and local trade/health licence coordinated together.',
  service_explainer = '{"steps":[{"step":1,"title":"What it is","visual":"info","body":"Cloud Kitchen Setup is a bundled service that handles all mandatory licences for a delivery-only commercial kitchen: FSSAI State License (or Central License based on turnover), GST Registration, and local trade/health licence from your municipal authority. Unlike a restaurant, you do not need a seating permit, but food safety and tax registrations apply in full."},{"step":2,"title":"Why you need it","visual":"sparkles","body":"Food delivery platforms (Swiggy, Zomato, and others) will not onboard you without a valid FSSAI licence number. Without GST registration, you cannot issue compliant invoices to platforms or claim ITC on kitchen equipment and raw materials. Operating without a trade licence exposes you to closure notices from local authorities."},{"step":3,"title":"What happens without it","visual":"alert","body":"You cannot list on food delivery platforms - the primary revenue channel for cloud kitchens. Food safety officers can seal unlicensed premises. Penalty under FSSAI Act is up to Rs 5 lakh. Products can be seized. Insurance claims are rejected if you are operating without proper authorisation."}]}'::jsonb,
  workflow_stages = '[{"step":1,"title":"Business details and kitchen address","timeline":"Day 0","body":"Turnover, kitchen area, menu category, GST status. We determine the correct FSSAI licence type and local authority requirements for your location.","visual":"checklist","milestone":"Compliance expert assigned, licence types confirmed"},{"step":2,"title":"Upload documents through the app","timeline":"Day 0-2","body":"Business registration proof, kitchen layout plan, food safety plan, equipment list, address proof, and owner ID.","visual":"upload","milestone":"Documents verified"},{"step":3,"title":"FSSAI application filed","timeline":"Day 2-5","body":"Form B filed on the FSSAI portal. ARN generated and shared.","visual":"form","milestone":"FSSAI application submitted"},{"step":4,"title":"GST registration filed (if not already registered)","timeline":"Day 2-5","body":"GST REG-01 filed in parallel. ARN shared same day.","visual":"form","milestone":"GST application submitted"},{"step":5,"title":"Local trade/health licence application","timeline":"Day 3-7","body":"Application filed with your municipal authority. Requirements vary by city.","visual":"form","milestone":"Trade licence application filed"},{"step":6,"title":"Inspection coordinated (FSSAI State/Central)","timeline":"Day 7-14","body":"State and Central FSSAI licences require a physical inspection. We provide a pre-inspection checklist: hygiene standards, pest control certificate, water test report, equipment labels.","visual":"calendar","milestone":"Inspection completed"},{"step":7,"title":"All licences issued","timeline":"Day 10-21","body":"FSSAI licence number, GSTIN, and trade licence received. All uploaded to your account.","visual":"stamp","milestone":"Kitchen ready to list on platforms","isCompletion":true}]'::jsonb,
  whats_included = '[{"title":"FSSAI licence - correct type determined upfront","body":"Basic Registration (up to Rs 12 lakh turnover), State License (Rs 12 lakh to Rs 20 crore), or Central License (above Rs 20 crore or multi-state). We confirm the right type before you pay the government fee."},{"title":"GST registration","body":"Full GST registration process including CA assignment, document verification, and ARN tracking. Included in the bundle."},{"title":"Local trade/health licence","body":"Filed with your municipal authority. Requirements differ by city - Delhi, Mumbai, Bangalore each have different processes. We handle your specific city."},{"title":"Pre-inspection checklist","body":"For State and Central FSSAI licences, we provide a checklist of what inspectors check: pest control certificate, water testing, equipment hygiene, food safety plan. Reduces the risk of inspection failure."},{"title":"Renewal tracking","body":"FSSAI licence is valid for 1-5 years (you choose at application). Renewal reminder added to your compliance calendar."}]'::jsonb,
  service_risks = '[{"icon":"alert","title":"FSSAI inspection failure","body":"State and Central licences require physical inspection. Common failure points: no pest control certificate, missing water quality test, equipment without hygiene labels. Our pre-inspection checklist addresses all of these."},{"icon":"document","title":"Wrong FSSAI licence type","body":"Applying for Basic Registration when you need a State Licence gets rejected. We verify your turnover and operation type before filing."},{"icon":"mismatch","title":"GST Aadhaar OTP failure","body":"GST registration requires Aadhaar-based authentication. If your linked mobile is inactive, OTP fails. We verify this before filing."}]'::jsonb,
  profile_personas = '[{"label":"New cloud kitchen, no existing licences","detail":"Starting from scratch. All three licences handled together."},{"label":"Home baker scaling to commercial","detail":"Moving from home to a commercial kitchen. State Licence now required."},{"label":"Already have GST, need FSSAI","detail":"Partial bundle - FSSAI and trade licence only."},{"label":"Multi-city expansion","detail":"New kitchen location in a new city. Fresh local licences required for each location."}]'::jsonb,
  faqs = '[{"category":"General","q":"Do I need FSSAI even for a small kitchen?","a":"Yes. All food businesses need FSSAI. Below Rs 12 lakh turnover: Basic Registration. Above: State or Central License. No exemptions for cloud kitchens."},{"category":"General","q":"Can I list on Swiggy or Zomato before getting licences?","a":"No. Both platforms require FSSAI licence number at onboarding. You cannot list without it."},{"category":"General","q":"What is the difference between FSSAI Registration and State License?","a":"Basic Registration: turnover below Rs 12 lakh, no inspection. State License: Rs 12 lakh to Rs 20 crore, inspection required. Central License: above Rs 20 crore or operating across multiple states."},{"category":"Process","q":"How long is the FSSAI licence valid?","a":"1 to 5 years - you choose at the time of application. Renewal must be applied for before expiry."},{"category":"Process","q":"Does a cloud kitchen need a separate address for each brand?","a":"No. Multiple brands (virtual restaurants) can operate from one kitchen under one FSSAI licence at one address."},{"category":"Documents","q":"What documents are needed?","a":"Business registration, owner ID and address proof, kitchen layout plan, food safety plan, equipment list, and pest control certificate for State/Central applications."}]'::jsonb
WHERE slug = 'cloud-kitchen-setup';
