// ─── INCOME TAX NOTICE PAGES 10-19 ──────────────────────────────────────────

// ─── 10. Section 143(1) Intimation ───────────────────────────────────────────

export const it1431Updates = {
  slug: 'income-tax-143-1-intimation',
  seoTitle: 'Income Tax 143(1) Intimation Explained (2025) | Ollvy',
  seoDescription: 'A 143(1) intimation confirms your return has been processed by the CPC. If there is a tax demand, verify the computation and pay or file a rectification request within 30 days.',

  sections: [
    {
      number: '01',
      heading: 'WHAT A 143(1) INTIMATION ACTUALLY IS',
      body: 'A 143(1) intimation is generated by the Centralised Processing Centre (CPC) after your Income Tax Return is processed. It is not a scrutiny notice and it does not ask for documents or explanations. It is the department\'s computation of your tax based on what you filed.\n\nThe intimation shows total income as computed by the CPC, tax payable or refund due, and any adjustments the CPC made to your filed return.',
      note: 'Source: Section 143(1), Income Tax Act 1961. Every return filed is processed under this section within 9 months of filing.',
    },
    {
      number: '02',
      heading: 'WHAT THE INTIMATION CONTAINS',
      body: 'The intimation shows your filed income figures alongside the CPC-adjusted figures if any adjustments were made. It shows tax computed by the CPC, TDS and advance tax credit allowed, net tax payable or refund due, and interest under Sections 234A, 234B, or 234C if applicable.\n\nIf the CPC-adjusted figures match what you filed and the refund or demand is as expected, no action is needed. The issue arises when there is a discrepancy.',
    },
    {
      number: '03',
      heading: 'COMMON REASONS FOR ADJUSTMENTS',
      body: '',
      bullets: [
        'Arithmetic errors in your return',
        'Incorrect claim of deduction (e.g., 80C claim exceeds the limit)',
        'Mismatch between TDS claimed and Form 26AS or AIS data',
        'Disallowance of expenses that require supporting documents',
        'Income added from AIS or TIS that you did not declare',
      ],
    },
    {
      number: '04',
      heading: 'IF THERE IS A TAX DEMAND',
      body: 'If the intimation shows tax payable, verify the computation first. Is the CPC\'s adjustment correct?\n\nIf correct: pay the demand through the e-filing portal using Challan 280.\n\nIf incorrect: file a rectification request under Section 154 within 30 days.\n\nInterest will accrue on unpaid demands, so act quickly either way.',
    },
    {
      number: '05',
      heading: 'HOW TO FILE A RECTIFICATION REQUEST',
      body: 'File a rectification request (Section 154) through the e-filing portal: Login > e-File > Rectification > New Request. Select the assessment year and type of rectification. Upload supporting documents showing why the adjustment is wrong.\n\nThe CPC will process the rectification and issue a revised intimation. For genuine CPC errors, this is usually resolved within 30 to 60 days. Rectification is free and done online.',
    },
    {
      number: '06',
      heading: 'THE DIFFERENCE BETWEEN 143(1) AND A SCRUTINY NOTICE',
      body: 'Many taxpayers confuse 143(1) with a scrutiny notice and panic unnecessarily. The distinction is important.\n\nA 143(1) intimation is automated. The CPC processes millions of returns using software. No officer has specifically reviewed your case. Adjustments are made based on data mismatches and arithmetic checks.\n\nA 143(2) scrutiny notice means a human Assessing Officer has selected your return for detailed examination. That is a different matter entirely and requires professional help.\n\nIf what you received says "143(1)" at the top, you are dealing with a processing adjustment, not a scrutiny.',
    },
  ],

  faqs: [
    {
      q: 'The 143(1) intimation shows a refund. Do I need to do anything?',
      a: 'If the refund amount matches what you expected, no action is needed. The refund will be credited to your bank account. Verify your bank details are correct in your e-filing profile. If the refund is less than expected, check whether the CPC made adjustments.',
    },
    {
      q: 'I received 143(1) but my return shows "pending" on the portal. Why?',
      a: 'The intimation is generated after processing. If you received it, your return has been processed. The portal status may take a few days to update. Check again after 24 to 48 hours.',
    },
    {
      q: 'The adjustment seems wrong but the amount is small. Should I still file a rectification?',
      a: 'Yes, especially if the adjustment involves a wrong TDS credit or an incorrect disallowance. Small errors can affect future assessments. Filing a rectification is free and straightforward.',
    },
  ],

  sources: [
    {
      name: 'Income Tax Act, 1961 (Section 143(1))',
      url: 'https://www.incometax.gov.in',
      description: 'Processing of returns by CPC and intimation to taxpayer',
    },
    {
      name: 'Income Tax e-Filing Portal',
      url: 'https://eportal.incometax.gov.in',
      description: 'Official portal for filing rectification requests and checking intimation status',
    },
  ],
}


// ─── 11. Section 143(2) Scrutiny Notice ──────────────────────────────────────

export const it1432Updates = {
  slug: 'income-tax-143-2-scrutiny',
  seoTitle: 'Income Tax 143(2) Scrutiny Notice: How to Respond (2025) | Ollvy',
  seoDescription: 'A 143(2) notice means your return has been selected for detailed examination by an Assessing Officer. Respond within the deadline. Missing it leads to an adverse assessment under 143(3).',

  sections: [
    {
      number: '01',
      heading: 'YOUR RETURN HAS BEEN SELECTED FOR SCRUTINY',
      body: 'A 143(2) notice means the Assessing Officer (AO) has selected your return for detailed examination. Unlike 143(1) which is automated, 143(2) involves a human officer reviewing your return and supporting documents.\n\nThis notice must be issued within 3 months from the end of the financial year in which the return was filed, or within 3 months from the date of filing for belated returns.',
      note: 'Source: Section 143(2), Income Tax Act 1961. Scrutiny assessments are completed under Section 143(3).',
    },
    {
      number: '02',
      heading: 'WHY RETURNS GET SELECTED FOR SCRUTINY',
      body: '',
      bullets: [
        'CASS (Computer Assisted Scrutiny Selection): returns selected based on risk parameters such as high cash deposits, significant capital gains, large deductions, or turnover thresholds',
        'Specific information: the department received information about you from third parties (banks, registrars, foreign tax authorities)',
        'Random selection: a small percentage of returns are selected randomly each year',
        'Mismatch with AIS or TIS: income reported in your Annual Information Statement does not match your return',
      ],
    },
    {
      number: '03',
      heading: 'THE SCRUTINY PROCESS FROM START TO FINISH',
      body: 'Initial notice (143(2)): asks you to appear or submit documents.\n\nQuestionnaire: the AO issues specific questions about income, deductions, and investments.\n\nDocument submission: you provide books of accounts, bank statements, contracts, and invoices.\n\nHearings: you or your CA appears before the AO to explain and clarify.\n\nDraft assessment: the AO shares a proposed assessment with adjustments.\n\nFinal order (143(3)): the assessment order is passed with or without additions to income.\n\nThe entire process typically takes 6 to 18 months depending on complexity.',
    },
    {
      number: '04',
      heading: 'WHAT DOCUMENTS YOU NEED TO PREPARE',
      body: 'The moment you receive a 143(2) notice, start compiling these regardless of what the notice specifically asks for:\n\nBooks of accounts for the relevant assessment year. Bank statements for all accounts (savings, current, FD). Income proofs: salary slips, business invoices, rental agreements, investment statements. Deduction proofs: 80C receipts, home loan certificates, medical insurance premiums. Form 26AS and AIS for the relevant year. Any contracts, agreements, or correspondence related to large transactions.\n\nHaving these ready before the first hearing significantly reduces the back-and-forth and shortens the process.',
    },
    {
      number: '05',
      heading: 'HOW TO RESPOND',
      body: 'Engage a CA or tax professional immediately. Scrutiny is not DIY territory.\n\nCompile all documents mentioned in the notice. Respond within the deadline (request an extension in writing before the deadline if needed). Be factual and precise. Do not volunteer extra information beyond what is asked. Maintain a record of all submissions and correspondence.',
    },
    {
      number: '06',
      heading: 'POSSIBLE OUTCOMES',
      body: 'No addition: the AO accepts your return as filed. Assessment order reflects your declared income.\n\nAddition with your agreement: the AO finds an issue, you agree and pay the additional tax.\n\nAddition without agreement: the AO adds income, you disagree and plan to appeal to CIT(Appeals) within 30 days.\n\nPenalty proceedings: if the AO believes there was concealment or furnishing of inaccurate particulars, penalty proceedings under Section 270A or 271(1)(c) may be initiated.',
      note: 'If there are additions, you have 30 days to file an appeal to the CIT(Appeals). Paying 20 percent of the demand may be required to stay recovery during appeal.',
    },
  ],

  faqs: [
    {
      q: 'I received 143(2) but I have filed my return correctly. Should I still be worried?',
      a: 'Selection for scrutiny does not mean the department suspects wrongdoing. Many scrutinies end with the return being accepted as filed. However, you must respond properly and on time. Engage a CA to ensure your response is complete and professional.',
    },
    {
      q: 'Can I handle scrutiny without a CA?',
      a: 'Technically yes, but not recommended. The scrutiny process involves legal and procedural nuances. A professional knows how to present your case, what documents to submit, and what arguments carry weight. The cost of a CA is usually less than the cost of adverse additions due to poor handling.',
    },
    {
      q: 'How long does the scrutiny process take?',
      a: 'Scrutiny assessments must be completed within 12 months from the end of the assessment year. For cases involving international transactions, the limit is 24 months. In practice, most cases are resolved within 6 to 18 months.',
    },
  ],

  sources: [
    {
      name: 'Income Tax Act, 1961 (Section 143(2) and 143(3))',
      url: 'https://www.incometax.gov.in',
      description: 'Scrutiny assessment notice issuance and assessment order provisions',
    },
    {
      name: 'Income Tax e-Filing Portal (e-Proceedings)',
      url: 'https://eportal.incometax.gov.in',
      description: 'Portal for responding to scrutiny notices and submitting documents',
    },
  ],
}


// ─── 12. Section 142(1) Notice ────────────────────────────────────────────────

export const it1421Updates = {
  slug: 'income-tax-142-1-notice',
  seoTitle: 'Income Tax 142(1) Notice: How to Respond (2025) | Ollvy',
  seoDescription: 'A 142(1) notice is a request for specific information or documents from the Assessing Officer. Ignoring it leads to a best judgment assessment under Section 144 and a Rs. 10,000 penalty.',

  sections: [
    {
      number: '01',
      heading: 'WHAT IS A 142(1) NOTICE',
      body: 'A 142(1) notice is issued by the Assessing Officer to ask you to file a return if you have not filed one, or to request specific information, documents, or accounts for assessment purposes.\n\nIt is an information-gathering notice, not a demand for tax. The officer is asking for clarity before deciding whether any additions need to be made.',
      note: 'Source: Section 142(1), Income Tax Act 1961.',
    },
    {
      number: '02',
      heading: 'THREE TYPES OF 142(1) NOTICES',
      body: 'Inquiry before assessment: issued during scrutiny to request specific documents.\n\nNotice to non-filers: issued to persons who have not filed a return but should have, based on high-value transactions, TDS credits, or other data the department holds.\n\nPre-scrutiny inquiry: issued to gather information before deciding whether to issue a 143(2) scrutiny notice.',
    },
    {
      number: '03',
      heading: 'HOW TO RESPOND',
      body: 'Read the notice carefully. It will specify exactly what documents or information is required. Compile the requested documents. Submit online through the e-filing portal under Compliance > e-Proceedings.\n\nIf you need more time, request an adjournment before the deadline. Keep a copy of everything you submit.',
    },
    {
      number: '04',
      heading: 'IF YOU DO NOT RESPOND',
      body: 'The consequences of ignoring a 142(1) notice are serious.',
      bullets: [
        'Best judgment assessment: the AO can assess your income based on available information without your input under Section 144',
        'Penalty: Rs. 10,000 for failure to comply with a 142(1) notice under Section 272A',
        'Prosecution: repeated non-compliance can lead to prosecution under Section 276D',
      ],
    },
    {
      number: '05',
      heading: 'HOW A 142(1) NOTICE FITS INTO THE ASSESSMENT TIMELINE',
      body: 'A 142(1) notice is almost always a precursor to something larger. Understanding where it sits in the assessment process helps you prioritise your response.\n\nIf you have not filed a return: the notice gives you a final opportunity before the AO does a best judgment assessment based on third-party data. Filing at this stage, even late, is almost always better than letting the AO assess you.\n\nIf you have filed a return: the notice means the AO is examining something specific. This is either a pre-step to a 143(2) scrutiny notice or a standalone inquiry. A complete, well-documented response often ends the matter here without escalating to formal scrutiny.',
    },
    {
      number: '06',
      heading: 'WHAT NOT TO DO',
      body: '',
      bullets: [
        'Do not ignore the notice',
        'Do not submit incomplete information hoping the AO will not notice',
        'Do not submit documents that contradict your filed return without explanation',
        'Do not miss the deadline without requesting an extension',
        'Do not fabricate documents: that is a criminal offence under the Income Tax Act',
      ],
    },
  ],

  faqs: [
    {
      q: 'I already filed my return. Why am I getting a 142(1) notice?',
      a: 'The notice may be asking for supporting documents related to your filed return (income sources, deduction proofs, bank statements). The AO wants to verify what you declared.',
    },
    {
      q: 'The notice asks for documents I do not have. What do I do?',
      a: 'Submit what you have and clearly explain in your response which documents are unavailable and why. Provide alternative evidence if possible. Do not submit fabricated documents.',
    },
    {
      q: 'I received a 142(1) notice but I never got a 143(2) notice. Is that normal?',
      a: 'Yes. A 142(1) notice can be issued before 143(2) as a pre-scrutiny inquiry, or independently for non-filers. You do not need to have received a 143(2) notice first.',
    },
  ],

  sources: [
    {
      name: 'Income Tax Act, 1961 (Section 142(1))',
      url: 'https://www.incometax.gov.in',
      description: 'Information request provision before assessment',
    },
    {
      name: 'Income Tax Act, 1961 (Section 144 and 272A)',
      url: 'https://incometaxindia.gov.in/acts/income-tax-act-1961.pdf',
      description: 'Best judgment assessment and penalty for non-compliance with 142(1)',
    },
  ],
}


// ─── 13. Section 148/148A Reopening ──────────────────────────────────────────

export const it148Updates = {
  slug: 'income-tax-148-148a-reopening',
  seoTitle: 'Income Tax 148/148A Reopening Notice: How to Respond (2025) | Ollvy',
  seoDescription: 'A 148A notice means the Income Tax department wants to reopen your past assessment for income it believes escaped tax. Your response to 148A is your best chance to stop it.',

  sections: [
    {
      number: '01',
      heading: 'WHAT REOPENING MEANS',
      body: 'A 148 or 148A notice means the Income Tax department wants to reassess an assessment year that was already completed. They believe income has "escaped assessment," meaning income that should have been taxed was not.\n\nThe law changed significantly in 2021. Before issuing a 148 notice, the AO must first issue a 148A notice giving you an opportunity to respond.',
      note: 'Source: Sections 147, 148, 148A, Income Tax Act 1961 (as amended by Finance Act 2021).',
    },
    {
      number: '02',
      heading: 'THE TWO-STEP PROCESS AFTER 2021',
      body: 'Step 1: 148A(b) Notice. The AO sends you a notice stating why they believe income has escaped assessment. You get a hearing opportunity.\n\nYour response: submit your objections with supporting documents within the deadline (typically 7 to 30 days).\n\n148A(d) Order: the AO considers your response and decides whether to proceed. They must pass a speaking order giving reasons.\n\nStep 2: 148 Notice. If the AO decides to proceed, they issue a 148 notice requiring you to file a return for the relevant year.',
    },
    {
      number: '03',
      heading: 'TIME LIMITS FOR REOPENING',
      body: '3 years: if income escaped assessment is less than Rs. 50 lakh.\n\n10 years: if income escaped assessment is Rs. 50 lakh or more and the AO has evidence of asset, expenditure, or deposit in a bank account outside the books.\n\nThese time limits run from the end of the relevant assessment year. If the notice is beyond these limits, time-bar is a strong procedural ground for your 148A response.',
    },
    {
      number: '04',
      heading: 'HOW TO RESPOND TO 148A',
      body: 'Your response to 148A is your first and best opportunity to prevent reopening.',
      bullets: [
        'Address each ground mentioned in the notice specifically with documentary evidence',
        'Provide evidence that the income was already assessed or did not escape assessment',
        'Cite legal provisions and case law supporting your position',
        'If there are procedural defects (wrong year, wrong ground, time-barred), raise them clearly',
        'Engage a CA or tax lawyer: 148A responses require legal precision',
      ],
    },
    {
      number: '05',
      heading: 'COMMON GROUNDS TO CHALLENGE A REOPENING',
      body: 'Reopening is not automatic just because the AO suspects something. There are well-established grounds on which reopenings are regularly quashed by courts and tribunals.\n\nChange of opinion: if the AO reviewed the same material during the original assessment and is now reconsidering the same facts, reopening is not valid.\n\nTime-barred: if the notice falls outside the 3-year or 10-year limit, it can be challenged on this ground alone.\n\nNo tangible new material: the AO must have specific new information that was not available during the original assessment. A mere suspicion or a tip without supporting evidence is insufficient.\n\nInadequate reasons in 148A(d) order: the AO must give detailed reasons for proceeding. A generic or boilerplate order can be challenged.',
    },
    {
      number: '06',
      heading: 'AFTER 148 IS ISSUED',
      body: 'If the 148 notice is issued after considering your 148A response, you must file a return for the relevant year even if you already filed one for that year. This return will be treated as a fresh return. The AO will conduct assessment proceedings. You retain the right to challenge the reopening itself through appeal or writ petition.',
      note: 'Many reopenings are quashed by courts on procedural grounds. A tax professional can assess whether your case has such grounds.',
    },
  ],

  faqs: [
    {
      q: 'Can they reopen my return just because they disagree with my tax position?',
      a: 'No. Change of opinion is not a valid ground for reopening. The AO must have new information that was not available or considered during the original assessment. If the reopening is based purely on re-examining the same material, it can be challenged.',
    },
    {
      q: 'I received a 148A notice for AY 2018-19. Is that time-barred?',
      a: 'It depends on the amount of escaped income alleged and the nature of evidence. For less than Rs. 50 lakh, 3 years is the limit (making AY 2018-19 potentially time-barred for regular cases as of 2025). Check with a CA for your specific situation and any COVID-related extensions that may apply.',
    },
    {
      q: 'The 148A notice mentions a large cash deposit in my bank. I can explain it. Should I respond or wait?',
      a: 'Respond immediately with full documentation. A well-documented 148A response (bank statements, source of funds, filed return showing the income) often stops the reopening at this stage without a 148 notice being issued.',
    },
  ],

  sources: [
    {
      name: 'Income Tax Act, 1961 (Sections 147, 148, 148A)',
      url: 'https://www.incometax.gov.in',
      description: 'Reassessment provisions as amended by Finance Act 2021',
    },
    {
      name: 'Finance Act 2021',
      url: 'https://incometaxindia.gov.in/acts/income-tax-act-1961.pdf',
      description: 'Amendment introducing the mandatory 148A pre-notice requirement',
    },
  ],
}


// ─── 14. Section 139(9) Defective Return ─────────────────────────────────────

export const it1399Updates = {
  slug: 'income-tax-139-9-defective-return',
  seoTitle: 'Income Tax 139(9) Defective Return Notice: How to Respond (2025) | Ollvy',
  seoDescription: 'A 139(9) defective return notice means your ITR has technical errors. If you do not respond within 15 days, your return is treated as invalid, as if you never filed.',

  sections: [
    {
      number: '01',
      heading: 'YOUR RETURN HAS BEEN MARKED AS DEFECTIVE',
      body: 'A 139(9) notice means the CPC found technical defects in your filed return that make it incomplete or inconsistent. Common defects include using the wrong ITR form, missing schedules or annexures, arithmetic inconsistencies, P&L or Balance Sheet not attached for business returns, incomplete bank account details, and missing foreign asset disclosures when required.',
      note: 'Source: Section 139(9), Income Tax Act 1961.',
    },
    {
      number: '02',
      heading: 'WHAT HAPPENS IF YOU DO NOT RESPOND',
      body: 'If you fail to respond within 15 days, your return is treated as invalid. You are considered to have not filed a return for that year. You lose the ability to carry forward losses. If you had claimed a refund, it will not be processed. Late filing fees and penalties may apply as if you never filed.',
    },
    {
      number: '03',
      heading: 'HOW TO RESPOND',
      body: 'Login to the e-filing portal. Go to e-File > e-Proceedings > View Notices/Orders. Click "Submit Response" against the defective notice. Fix the defect as specified in the notice. Submit the corrected return or information.',
      note: 'You can request one extension of 15 days if you need more time. Submit the request before the original deadline expires.',
    },
    {
      number: '04',
      heading: 'COMMON DEFECTS AND HOW TO FIX THEM',
      body: '',
      bullets: [
        'Wrong ITR form: file a revised return using the correct form',
        'Missing P&L or Balance Sheet: upload the missing financial statements',
        'Bank account details incomplete: provide the complete IFSC and account number',
        'Arithmetic error: correct the calculation in the relevant schedule',
        'Foreign asset not declared: file revised return with Schedule FA completed',
        'Wrong regime selection (old vs new tax regime): file revised return with the correct regime',
      ],
    },
    {
      number: '05',
      heading: 'HOW TO AVOID A DEFECTIVE RETURN NOTICE IN FUTURE',
      body: 'Most defective return notices are caused by the same few errors year after year. Here is how to avoid them.\n\nUse the correct ITR form: the form depends on your income sources. ITR-1 is only for salaried individuals with income below Rs. 50 lakh and no capital gains. If you have capital gains, rental income from more than one property, or foreign income, you need ITR-2 or ITR-3.\n\nAttach all schedules: if you have a business, the P&L and Balance Sheet are mandatory. If you have foreign assets, Schedule FA is mandatory regardless of whether there was income from those assets.\n\nVerify bank details: wrong account numbers delay refunds and trigger defective return notices.\n\nReconcile TDS with Form 26AS before filing: TDS mismatches are one of the most common triggers for CPC adjustments and defective notices.',
    },
  ],

  faqs: [
    {
      q: 'I submitted the response but the portal still shows defective. What now?',
      a: 'Processing takes 15 to 30 days. If the status does not update after 30 days, raise a grievance on the e-filing portal under Grievance > Submit Grievance.',
    },
    {
      q: 'Can I file a revised return instead of responding to the defective notice?',
      a: 'Yes, but only if you are within the time limit for filing revised returns (before December 31 of the assessment year). If you are past that date, you must respond to the defective notice specifically.',
    },
    {
      q: 'I got a defective notice for using ITR-1 when I should have used ITR-2. How do I fix this?',
      a: 'File a revised return using ITR-2 if you are within the December 31 deadline. If not, respond to the defective notice through e-Proceedings, select "Return Data Correction," and upload the correct ITR-2.',
    },
  ],

  sources: [
    {
      name: 'Income Tax Act, 1961 (Section 139(9))',
      url: 'https://www.incometax.gov.in',
      description: 'Defective return notice provisions and response procedure',
    },
    {
      name: 'Income Tax e-Filing Portal',
      url: 'https://eportal.incometax.gov.in',
      description: 'Portal for responding to defective return notices via e-Proceedings',
    },
  ],
}


// ─── 15. Section 156 Demand Notice ───────────────────────────────────────────

export const it156Updates = {
  slug: 'income-tax-156-demand',
  seoTitle: 'Income Tax 156 Demand Notice: How to Respond (2025) | Ollvy',
  seoDescription: 'An Income Tax 156 demand notice means you owe tax following an assessment order. Verify the computation before paying. Unpaid demands attract interest at 1 percent per month.',

  sections: [
    {
      number: '01',
      heading: 'WHAT IS A 156 DEMAND NOTICE',
      body: 'A demand notice under Section 156 is issued when the Income Tax department has computed that you owe tax. This follows an assessment order under Section 143(3), 144, 147, or other sections.\n\nThe notice specifies the amount of tax payable, interest payable under Sections 234A, 234B, or 234C, penalty if any, and the due date for payment (usually 30 days).',
      note: 'Source: Section 156, Income Tax Act 1961.',
    },
    {
      number: '02',
      heading: 'VERIFY BEFORE YOU PAY',
      body: 'Before paying the demand, check the assessment order that generated it. Verify whether TDS credits have been correctly allowed. Check if all deductions you claimed have been accepted. Confirm the computation of interest is correct. If there are obvious errors, file for rectification under Section 154 before paying.',
    },
    {
      number: '03',
      heading: 'YOUR OPTIONS FOR RESPONDING',
      body: 'Pay in full: if the demand is correct, pay through the e-filing portal.\n\nPay under protest: if you disagree but want to avoid interest, pay and file an appeal.\n\nFile rectification: if there are obvious errors in the computation.\n\nFile appeal: if you disagree with the additions made by the AO, appeal to CIT(Appeals) within 30 days.\n\nRequest instalment or stay: if you cannot pay immediately.',
    },
    {
      number: '04',
      heading: 'HOW INTEREST IS CALCULATED ON UNPAID DEMANDS',
      body: 'Interest on unpaid demands under Section 220(2) is 1 percent per month or part of a month. There is no cap. This accrues from the day after the 30-day due date until the date of payment.\n\nOn a Rs. 10 lakh demand, unpaid for 12 months, the interest alone is Rs. 1.20 lakh. On a Rs. 50 lakh demand, it is Rs. 6 lakh per year.\n\nIf you are filing an appeal, paying 20 percent of the demand upfront and requesting a stay on the rest stops interest from accruing on the stayed portion.',
    },
    {
      number: '05',
      heading: 'IF YOU CANNOT PAY IMMEDIATELY',
      body: 'Request instalment payment by writing to the AO explaining your financial situation.\n\nRequest stay of demand pending appeal: if you have filed an appeal, request that recovery be stayed until the appeal is decided. You may need to pay 20 percent upfront.',
    },
    {
      number: '06',
      heading: 'WHAT HAPPENS IF YOU DO NOT PAY',
      body: '',
      bullets: [
        'Interest: 1 percent per month on the outstanding amount with no cap',
        'Attachment of bank account: the Tax Recovery Officer can attach your bank accounts',
        'Attachment of salary: your employer can be directed to deduct from your salary',
        'Attachment of property: in extreme cases, property can be attached and sold',
        'Certificate proceedings: the AO can issue a certificate to the Tax Recovery Officer for recovery as arrears of land revenue',
      ],
    },
  ],

  faqs: [
    {
      q: 'The demand is for Rs. 50 lakh but I only earn Rs. 10 lakh per year. This must be wrong.',
      a: 'Large demands often result from AO additions during assessment. Check the assessment order. If additions were made incorrectly, file an appeal. You may need to pay 20 percent to get a stay on recovery during appeal.',
    },
    {
      q: 'I already paid my taxes when I filed. Why is there a demand?',
      a: 'The demand may be for additional tax due to disallowed deductions, additions to income, or interest. Compare the assessment order with your filed return to understand what changed.',
    },
    {
      q: 'Can I pay part of the demand now and the rest later?',
      a: 'Yes, but interest continues to accrue on the unpaid portion. If you are filing an appeal, pay 20 percent of the total demand and request a stay on the remaining 80 percent. This stops recovery action on the stayed amount while your appeal is pending.',
    },
  ],

  sources: [
    {
      name: 'Income Tax Act, 1961 (Section 156)',
      url: 'https://www.incometax.gov.in',
      description: 'Demand notice issuance following assessment orders',
    },
    {
      name: 'Income Tax Act, 1961 (Section 220(2))',
      url: 'https://incometaxindia.gov.in/acts/income-tax-act-1961.pdf',
      description: 'Interest on delayed payment of tax demands at 1 percent per month',
    },
  ],
}


// ─── 16. Section 245 Refund Adjustment ───────────────────────────────────────

export const it245Updates = {
  slug: 'income-tax-245-refund-adjustment',
  seoTitle: 'Income Tax 245 Refund Adjustment Notice: What to Do (2025) | Ollvy',
  seoDescription: 'A 245 notice means your Income Tax refund is being adjusted against a pending demand. Verify the underlying demand within 30 days or the adjustment happens automatically.',

  sections: [
    {
      number: '01',
      heading: 'WHAT IS HAPPENING',
      body: 'A 245 notice means you have a refund due from a return you filed and you also have an outstanding tax demand from a previous year or current processing. The department is proposing to adjust your refund against that demand.\n\nThis is called "set off." The department wants to use your refund to pay your outstanding dues.',
      note: 'Source: Section 245, Income Tax Act 1961.',
    },
    {
      number: '02',
      heading: 'VERIFY THE UNDERLYING DEMAND FIRST',
      body: 'Before accepting or rejecting the adjustment, check your outstanding demands on the e-filing portal under Pending Actions > Response to Outstanding Demand. Verify if the demand is legitimate. Check if you have already paid it (old demands sometimes show as pending due to system errors). Check if the demand was reduced or deleted on appeal.',
    },
    {
      number: '03',
      heading: 'HOW TO RESPOND',
      body: 'If demand is correct: accept the adjustment by responding "Yes" on the portal.\n\nIf demand is incorrect: respond "No" and provide reasons. Already paid, paid under appeal, rectification pending, or demand is disputed are all valid grounds.\n\nIf partially correct: you can accept partial adjustment and dispute the rest.',
    },
    {
      number: '04',
      heading: 'TIME LIMIT AND WHAT HAPPENS IF YOU DO NOT RESPOND',
      body: 'You must respond within 30 days. If you do not respond, the adjustment is deemed accepted and will be processed automatically.\n\nThis means your refund will be applied to the outstanding demand without further notice. If the demand was incorrect, recovering the wrongly adjusted refund is a longer process involving rectification or appeal.',
    },
    {
      number: '05',
      heading: 'HOW TO TRACE OLD DEMANDS YOU DO NOT RECOGNISE',
      body: 'If the notice refers to a demand from several years ago that you do not recognise, here is how to trace it.\n\nCheck Form 26AS for TDS credits for that year on the e-filing portal. Pull up old returns from the e-filing portal under e-File > Income Tax Returns > View Filed Returns.\n\nIf the demand relates to an assessment order, search your records for the relevant year\'s 143(3) or 144 order. If it was appealed and won, locate the appellate order and submit it as proof.\n\nIf the demand seems to be a system error (showing as outstanding despite being paid), locate the old payment challan and submit it as evidence.',
    },
  ],

  faqs: [
    {
      q: 'The demand being adjusted is very old and I do not have records. What do I do?',
      a: 'Check Form 26AS for TDS credits for that year. Pull up old returns from the e-filing portal. If the demand is for an assessment that was appealed and won, submit proof of the appellate order.',
    },
    {
      q: 'Can I get my refund without the adjustment if I have filed an appeal against the demand?',
      a: 'You can request this, but it is at the AO\'s discretion. Generally, if you have paid 20 percent of the disputed demand, you may request that the rest of the refund be released pending appeal.',
    },
    {
      q: 'The adjustment notice is for a demand I paid last year. How do I prove it?',
      a: 'Locate the payment challan from your bank records or from the e-filing portal under e-Pay Tax > Payment History. Submit the challan number, BSR code, and date as part of your "No" response. The CPC will verify the payment and release your refund.',
    },
  ],

  sources: [
    {
      name: 'Income Tax Act, 1961 (Section 245)',
      url: 'https://www.incometax.gov.in',
      description: 'Set-off of refunds against outstanding demands',
    },
    {
      name: 'Income Tax e-Filing Portal',
      url: 'https://eportal.incometax.gov.in',
      description: 'Portal for responding to 245 notices under Pending Actions',
    },
  ],
}


// ─── 17. Section 271 Penalty Notice ──────────────────────────────────────────

export const it271Updates = {
  slug: 'income-tax-271-penalty',
  seoTitle: 'Income Tax 271/270A Penalty Notice: How to Respond (2025) | Ollvy',
  seoDescription: 'A penalty notice under Section 271 or 270A is separate from your assessment. Even if you paid the tax, you must respond. Penalty is not automatic and can be challenged.',

  sections: [
    {
      number: '01',
      heading: 'WHAT PENALTY PROCEEDINGS MEAN',
      body: 'Penalty notices are issued when the AO believes you concealed income, furnished inaccurate particulars of income, or under-reported or misreported income.\n\nThe penalty regime changed in 2016. For assessment years before AY 2017-18, Section 271(1)(c) applies. For AY 2017-18 onwards, Section 270A applies.',
      note: 'Source: Sections 270A, 271(1)(c), Income Tax Act 1961.',
    },
    {
      number: '02',
      heading: 'PENALTY RATES',
      body: 'Under Section 270A (current):\n\nUnder-reporting: 50 percent of tax payable on under-reported income.\nMisreporting: 200 percent of tax payable on misreported income.\n\nUnder Section 271(1)(c) (old, for years before AY 2017-18):\n\n100 percent to 300 percent of tax sought to be evaded.',
    },
    {
      number: '03',
      heading: 'DEFENCES AVAILABLE',
      body: 'Not all additions in assessment attract penalty. You can argue several grounds.',
      bullets: [
        'Bona fide mistake: you made an honest error with no intention to conceal',
        'Disclosed all material facts: you provided complete information and the disallowance is due to a difference of opinion',
        'Legal interpretation: you took a position based on a legitimate interpretation of law',
        'Additions are disputed: if the assessment additions are themselves being appealed, request that penalty be kept in abeyance',
        'Procedural defects: the penalty notice does not specify which limb (concealment vs inaccurate particulars)',
      ],
      note: 'The Supreme Court in Dilip Shroff vs JCIT held that penalty is not automatic just because an addition is made. The AO must prove that there was concealment or furnishing of inaccurate particulars.',
    },
    {
      number: '04',
      heading: 'THE DIFFERENCE BETWEEN UNDER-REPORTING AND MISREPORTING',
      body: 'Section 270A distinguishes between two categories of penalty, and the difference in rates is significant.\n\nUnder-reporting (50 percent penalty): applies when income declared is less than income assessed, typically because of a missed income source, wrong deduction claim, or an item the AO has added. This is the more common situation.\n\nMisreporting (200 percent penalty): applies to specific aggravated situations: misrepresentation or suppression of facts, failure to record investments in books, claiming false entries, or failure to report international transactions. The AO must specifically establish misreporting to apply the higher rate.\n\nIf the penalty notice does not clearly specify which category applies, challenge the specificity of the notice itself.',
    },
    {
      number: '05',
      heading: 'HOW TO RESPOND',
      body: 'Request more time if needed (before the deadline). Submit a detailed written reply addressing each point. Cite relevant case law supporting no penalty. If the underlying assessment is being appealed, request that penalty be kept in abeyance pending appeal. Appear for the hearing with your CA.',
    },
    {
      number: '06',
      heading: 'IF PENALTY IS LEVIED',
      body: 'You can appeal to CIT(Appeals) within 30 days of the penalty order. Penalty orders are frequently reversed or reduced at appellate stages.\n\nIf the underlying assessment addition is also being appealed, the penalty appeal should be coordinated with the assessment appeal. A successful appeal on the addition usually results in the penalty being deleted as well.',
    },
  ],

  faqs: [
    {
      q: 'The AO made additions and now wants penalty. Is penalty automatic?',
      a: 'No. Penalty is not automatic. The AO must independently establish that there was concealment or furnishing of inaccurate particulars. Many penalty orders are deleted on appeal because the AO failed to discharge this burden.',
    },
    {
      q: 'I declared all my income but the AO disallowed a deduction. Can they impose penalty?',
      a: 'Generally no. If you disclosed all facts and the disallowance is due to a legal interpretation, penalty should not apply. This is a strong defence, but you must argue it properly in your response.',
    },
    {
      q: 'I received both an assessment order and a penalty notice. Do I respond to both?',
      a: 'Yes, but separately. The assessment order is challenged through an appeal to CIT(Appeals). The penalty is challenged through a separate appeal or response. If you win the assessment appeal, the penalty typically follows. Always coordinate both with your CA.',
    },
  ],

  sources: [
    {
      name: 'Income Tax Act, 1961 (Sections 270A and 271(1)(c))',
      url: 'https://www.incometax.gov.in',
      description: 'Penalty provisions for under-reporting and misreporting of income',
    },
    {
      name: 'Supreme Court: Dilip Shroff vs JCIT',
      url: 'https://incometaxindia.gov.in',
      description: 'Landmark judgment establishing that penalty is not automatic on additions',
    },
  ],
}


// ─── 18. Section 131 Summons ──────────────────────────────────────────────────

export const it131Updates = {
  slug: 'income-tax-131-summons',
  seoTitle: 'Income Tax 131 Summons: What to Do (2025) | Ollvy',
  seoDescription: 'A 131 summons is a legal order requiring you to appear before the Income Tax officer or produce documents. Ignoring it is a prosecutable offence. You must respond.',

  sections: [
    {
      number: '01',
      heading: 'WHAT IS A 131 SUMMONS',
      body: 'A summons under Section 131 is a legal order requiring you to appear in person before the Income Tax officer, produce specific documents or evidence, or give evidence on oath.\n\nSection 131 gives the Income Tax officer powers similar to a civil court for compelling attendance and document production.',
      note: 'Source: Section 131, Income Tax Act 1961.',
    },
    {
      number: '02',
      heading: 'WHY YOU MAY HAVE RECEIVED THIS',
      body: '',
      bullets: [
        'You are a witness in someone else\'s investigation',
        'Your transactions appeared in another taxpayer\'s records',
        'You are the subject of an investigation, survey, or search',
        'The AO needs your testimony to complete an assessment',
      ],
    },
    {
      number: '03',
      heading: 'YOUR OBLIGATIONS',
      body: 'You must appear at the time and place specified. You must produce the documents specified in the summons. You may be examined on oath. False statements are perjury.\n\nIf you cannot appear on the specified date, request an adjournment in writing before the date. Do not ignore the summons and hope it goes away.',
    },
    {
      number: '04',
      heading: 'CONSEQUENCES OF NON-COMPLIANCE',
      body: '',
      bullets: [
        'Penalty under Section 272A: up to Rs. 10,000',
        'Prosecution under Section 276D: up to 1 year imprisonment',
        'Adverse inference: the AO can draw adverse conclusions from your non-appearance',
        'Warrant of arrest: in extreme cases of repeated non-compliance, the officer can issue a warrant',
      ],
    },
    {
      number: '05',
      heading: 'WHAT TO DO IF YOU ARE BEING SUMMONED AS A WITNESS',
      body: 'Being summoned as a witness in someone else\'s case is different from being summoned as a taxpayer under investigation. As a witness, you are required to answer questions truthfully and produce documents related to the transactions the officer is investigating.\n\nYou are not obligated to make any admission that might expose you to tax liability. If questions are directed at your own tax affairs, consult a lawyer before answering. You have the right to be accompanied by your authorised representative.\n\nDo not discuss the summons with the person under investigation before appearing. This can be construed as coordination and may create complications.',
    },
    {
      number: '06',
      heading: 'HOW TO PREPARE',
      body: 'Engage a CA or tax lawyer immediately. Collect all documents mentioned in the summons. Review your own tax filings for the relevant years. Prepare honest answers. Do not fabricate or mislead. Your authorised representative can accompany you but may not appear in your place if the summons requires personal attendance.',
    },
  ],

  faqs: [
    {
      q: 'Can I send my CA instead of appearing personally?',
      a: 'If the summons specifically requires your personal attendance, you must appear. Your CA can accompany you but cannot appear in your place. If the summons allows representation, your CA can appear with a valid power of attorney.',
    },
    {
      q: 'I do not have the documents they are asking for. What do I do?',
      a: 'Appear on the date and explain which documents you do not have and why. Submit whatever you do have. Do not submit fabricated documents.',
    },
    {
      q: 'The summons is related to a transaction from 8 years ago. How do I get records that old?',
      a: 'Check your bank statements (most banks keep records for 7 to 10 years and can provide certified copies). Check your email archives for invoices and contracts. Contact counterparties to the transaction for their records. If records genuinely do not exist, explain this clearly when you appear.',
    },
  ],

  sources: [
    {
      name: 'Income Tax Act, 1961 (Section 131)',
      url: 'https://www.incometax.gov.in',
      description: 'Power to take evidence, enforce attendance, and compel production of documents',
    },
    {
      name: 'Income Tax Act, 1961 (Section 272A and 276D)',
      url: 'https://incometaxindia.gov.in/acts/income-tax-act-1961.pdf',
      description: 'Penalty and prosecution for failure to comply with a 131 summons',
    },
  ],
}


// ─── 19. AIS/SFT Mismatch Notice ─────────────────────────────────────────────

export const itAisSftUpdates = {
  slug: 'income-tax-ais-sft-notice',
  seoTitle: 'Income Tax AIS/SFT Mismatch Notice: How to Respond (2025) | Ollvy',
  seoDescription: 'An AIS or SFT mismatch notice means the department found high-value transactions you may not have declared. Respond within the deadline or the case may be selected for scrutiny.',

  sections: [
    {
      number: '01',
      heading: 'WHAT IS AIS AND SFT',
      body: 'AIS (Annual Information Statement) contains information reported to the Income Tax department by third parties: banks, registrars, mutual funds, companies, and others.\n\nSFT (Statement of Financial Transactions) is the reporting mechanism by which specified entities report high-value transactions such as property purchases, mutual fund investments, fixed deposit interest, and cash deposits above specified thresholds.\n\nIf your ITR does not match the information in AIS or SFT, the department sends you a mismatch notice.',
      note: 'Source: Section 285BA, Income Tax Act 1961; Rule 114E, Income Tax Rules.',
    },
    {
      number: '02',
      heading: 'COMMON MISMATCHES',
      body: '',
      bullets: [
        'Property sale or purchase: SFT value differs from capital gains declared',
        'Bank interest: interest in AIS not matching interest declared in return',
        'Mutual fund transactions: capital gains from redemptions not declared',
        'Share transactions: securities transaction tax data not matching reported gains',
        'High-value cash deposits: bank deposits above Rs. 10 lakh flagged',
        'Foreign remittances: outward remittances under LRS not reflected in return',
      ],
    },
    {
      number: '03',
      heading: 'HOW TO CHECK YOUR AIS AND RESPOND',
      body: 'Login to the e-filing portal. Go to AIS > View your AIS. Review each transaction. For each mismatch, you can select "Accept" if the information is correct, or "Provide Feedback" if the information is incorrect or partially correct with an explanation.\n\nIf you need to revise your return based on AIS data, file a revised return if within the time limit.',
    },
    {
      number: '04',
      heading: 'WHY AIS DATA IS SOMETIMES WRONG',
      body: 'The AIS collects data from dozens of reporting entities automatically. Errors in AIS are not uncommon. The most frequent ones are:\n\nDuplicate entries: the same transaction reported by two different entities (e.g., both the buyer and the registrar reporting a property transaction).\n\nWrong PAN mapping: a third party filed a report with an incorrect PAN, which has been mapped to your account.\n\nStale data: a transaction that was reversed or cancelled but the reversal was not reported.\n\nDifferent valuation basis: the reporting entity used stamp duty value while you used actual sale consideration.\n\nIf AIS data is wrong, submit feedback on the portal explaining the error and contact the reporting entity (bank, registrar) to correct their records.',
    },
    {
      number: '05',
      heading: 'IF THE MISMATCH IS GENUINE',
      body: 'If you genuinely forgot to declare income shown in AIS, file an updated return under Section 139(8A). This is available for 2 years from the end of the assessment year with an additional tax of 25 percent (if filed in the first year) or 50 percent (if filed in the second year) on the incremental tax payable.\n\nAlternatively, respond to the notice explaining and offering to pay additional tax with interest. Proactive disclosure at this stage is treated more favourably than waiting for a scrutiny notice.',
    },
    {
      number: '06',
      heading: 'HOW AIS MISMATCHES LEAD TO SCRUTINY SELECTION',
      body: 'AIS mismatches are one of the primary inputs for CASS (Computer Assisted Scrutiny Selection). The system flags returns where declared income is significantly below what AIS data suggests.\n\nIf you respond to an AIS mismatch notice correctly and reconcile the difference, the flag is cleared and your return is less likely to be selected for scrutiny. If you ignore it, the mismatch remains and your return is at higher risk of being selected for 143(2) scrutiny in the next assessment cycle.',
    },
  ],

  faqs: [
    {
      q: 'I received AIS mismatch notice but I have already filed my return. What now?',
      a: 'If your filed return is correct and the AIS data is wrong, respond with feedback explaining the discrepancy. If the AIS data is correct and you missed declaring something, consider filing an updated return or responding with an offer to pay additional tax.',
    },
    {
      q: 'The AIS shows a property sale that I already declared in my return. Why the mismatch?',
      a: 'The mismatch may be due to a difference between sale consideration and stamp duty value, different date of registration vs date of sale, or indexation computation differences. Respond by explaining which figure you used and why.',
    },
    {
      q: 'AIS shows Rs. 5 lakh of interest income but I only received Rs. 3 lakh. What happened?',
      a: 'This often happens when fixed deposits are renewed: the bank reports the full interest credited including interest on the renewed FD, but you may have only received the net interest after TDS. Check your bank passbook or FD statement against the AIS entry and submit feedback if there is a genuine discrepancy.',
    },
  ],

  sources: [
    {
      name: 'Income Tax Act, 1961 (Section 285BA)',
      url: 'https://www.incometax.gov.in',
      description: 'Statement of Financial Transactions reporting requirement',
    },
    {
      name: 'Income Tax Rules (Rule 114E)',
      url: 'https://incometaxindia.gov.in/acts/income-tax-act-1961.pdf',
      description: 'High-value transactions required to be reported in SFT',
    },
  ],
}
