// AUTO-GENERATED from apps/customer/lib/email/templates/submission-complete.ts
// by scripts/sync-email-templates.mjs. Do NOT edit this file directly.
// Edit the source template, then run: node scripts/sync-email-templates.mjs

import { wrapHTML, ctaButton, mono } from './shared-layout.ts';
import { buildOrderUrl } from '../format.ts';

export interface SubmissionCompleteInput {
  customer_greeting: string;
  service_name: string;
  order_number: string;
  order_id: string;
  submitted_at_human: string;
  guaranteed_date: string;
}

const labelTd = 'padding: 4px 16px 4px 0; color: #666; white-space: nowrap; vertical-align: top;';
const valueTd = 'padding: 4px 0; vertical-align: top;';

export function buildSubmissionComplete(
  input: SubmissionCompleteInput
): { subject: string; html: string } {
  const subject = `We have everything. Work on your ${input.service_name} starts now (${input.order_number})`;

  const body = `
    <p>Hi ${input.customer_greeting},</p>
    <p>That is everything we needed. Thanks for completing the questionnaire and getting your documents in.</p>
    <p>Your order is with our team now and your guaranteed delivery date is live. You can see it any time on your order page.</p>
    <h3>Order details</h3>
    <table cellpadding="0" cellspacing="0" style="border-collapse: collapse; font-size: 14px;">
      <tr><td style="${labelTd}">Service</td><td style="${valueTd}">${input.service_name}</td></tr>
      <tr><td style="${labelTd}">Order number</td><td style="${valueTd}">${mono(input.order_number)}</td></tr>
      <tr><td style="${labelTd}">Submitted on</td><td style="${valueTd}">${mono(input.submitted_at_human)}</td></tr>
      <tr><td style="${labelTd}">Guaranteed by</td><td style="${valueTd}">${mono(input.guaranteed_date)}</td></tr>
    </table>
    <h3>What happens next</h3>
    <p>A specialist takes it from here. If we need anything else, we will email you and flag it on your order page. Otherwise, sit tight, we will keep you posted.</p>
    <p style="margin: 24px 0;">${ctaButton('View your order', buildOrderUrl(input.order_id))}</p>
    <p>Team Ollvy</p>
  `;

  return { subject, html: wrapHTML(body) };
}
