// =============================================================================
// GUIDE PAGE: income-tax-270-intimation
// File path: lib/guides/pages/income-tax-270-intimation.ts
// Section 270(1) intimation under the Income Tax Act 2025, successor to the
// Section 143(1) intimation for returns filed under the new Act. First mass
// wave expected after the July / August 2027 filing season.
// =============================================================================

import type { LearnPageConfig } from "../pages";

export const incomeTax270Intimation: LearnPageConfig = {
  slug: "income-tax-270-intimation",
  title: "Section 270(1) Intimation (Income Tax Act 2025): Demand, Refund, or No Change",
  seoTitle: "Section 270(1) Intimation (IT Act 2025) | Old 143(1) | Ollvy",
  seoDescription:
    "A Section 270(1) intimation is the Income-tax Act 2025 successor to 143(1): demand, refund, or no change. You get 30 days to respond to adjustments.",
  canonicalUrl: "https://www.ollvy.com/guides/income-tax-270-intimation",
  lastReviewed: "July 2026",
  category: "Income Tax Notice",
  relatedServiceSlugs: ["business-itr"],
  relatedLearnSlugs: [
    "income-tax-143-1-intimation",
    "income-tax-act-2025-section-mapping",
    "income-tax-280-281-reopening",
    "salaried-itr-2027",
  ],
  relatedTools: {
    penaltyCalculators: ["itr-late-filing"],
    documentChecklists: ["individual-itr", "business-itr"],
  },
  ctaServiceSlug: "business-itr",
  severity: "moderate",
  deadline: "30 days to respond to proposed adjustments",
  deadlineNote:
    "If the CPC proposes adjustments before finalising, you get 30 days to respond; no reply means the adjustment is made as proposed. If the intimation raises a demand, pay or contest within 30 days before interest starts.",
  sections: [
    {
      id: "01",
      heading: "WHAT A SECTION 270(1) INTIMATION IS",
      body:
        "A Section 270(1) intimation is the automated processing result for a return filed under the Income Tax Act 2025: the CPC's computation of your return, showing a demand, a refund, or no change. It is the new Act's successor to the Section 143(1) intimation, and it applies to returns filed under the 2025 Act, which in practice means the tax year 2026-27 returns filed from mid-2027 onwards. The first mass wave of 270(1) intimations will follow the July and August 2027 filing deadlines, which is exactly when searches for this unfamiliar section number spike. It is generated by the CPC's processing system, not by an officer examining your case, and receiving one is normal, not an accusation.",
    },
    {
      id: "02",
      heading: "270(1) vs THE OLD 143(1): WHAT ACTUALLY CHANGED",
      body:
        "Functionally, almost nothing. The scope of automated processing carries forward: arithmetic corrections, incorrect claims apparent from the return, disallowance of impermissible loss set-offs, TDS and tax-credit mismatches, and short-paid interest or fees. What changed is the packaging.",
      table: {
        headers: ["Aspect", "Old regime (1961 Act)", "New regime (2025 Act)"],
        rows: [
          ["Provision", "Section 143(1)", "Section 270(1)"],
          ["Applies to", "Returns for AY 2026-27 and earlier", "Returns filed under the 2025 Act (tax year 2026-27 onwards)"],
          ["Nature", "Automated CPC processing", "Automated CPC processing (unchanged)"],
          ["Tax credit statement checked", "Form 26AS", "Form 168 (renumbered 26AS)"],
          ["Demand enforcement", "Separate Section 156 demand notice concept", "Intimation with demand is deemed a notice of demand (Section 289)"],
        ],
      },
      note:
        "Your FY 2025-26 return filed in 2026 still gets a 143(1) intimation under the old Act. It is entirely possible to hold a 143(1) for one year and a 270(1) for the next; each is valid under its own Act.",
    },
    {
      id: "03",
      heading: "THE THREE OUTCOMES",
      body:
        "Open the intimation and find the comparison table: your figures in one column, the CPC's computation in the other. Three outcomes are possible:",
      bullets: [
        "Demand: the CPC computed higher tax than you paid and is asking for the difference. This needs action within 30 days.",
        "Refund: the CPC agrees you overpaid and initiates the refund to your pre-validated bank account. No action needed beyond confirming the credit arrives.",
        "No demand, no refund: the CPC's computation matches your return. Download it, file it away, done.",
      ],
      note:
        "The intimation with a demand is not a preliminary opinion you can sit on. Under Section 289 of the 2025 Act, an intimation showing an amount payable is deemed to be a notice of demand, so the recovery clock runs from it directly.",
    },
    {
      id: "04",
      heading: "PROPOSED ADJUSTMENTS: YOUR 30-DAY WINDOW BEFORE FINALISATION",
      body:
        "Where the CPC intends to adjust your return (for example, denying a deduction that looks inconsistent with the form, or aligning your TDS claim to Form 168), it must first communicate the proposed adjustment. You then get 30 days to respond through the e-filing portal. If you respond, the CPC must consider the reply before finalising. If you stay silent, the adjustment goes through as proposed and lands in the final intimation, usually as a demand. This pre-adjustment window existed under the old Act too and was widely ignored by taxpayers who did not check email; under the new Act, treat the adjustment communication as the real deadline, because contesting after finalisation means rectification, which is slower.",
    },
    {
      id: "05",
      heading: "WHY DEMANDS GET RAISED: THE USUAL SUSPECTS",
      body:
        "The processing logic is the same as it has always been, so the demand triggers are familiar:",
      bullets: [
        "TDS mismatch: you claimed more TDS than Form 168 shows against your PAN, usually because an employer or client filed their TDS return late or with errors. This remains the single most common trigger.",
        "Arithmetic and internal inconsistencies: totals that do not add up, deduction limits exceeded on the face of the return.",
        "Regime mismatch: deductions claimed that are not available under the regime selected in the return.",
        "Interest and fee recomputation: the CPC recalculates interest under Sections 423 to 425 (the old 234A/234B/234C) and the Section 426 late fee, and any shortfall becomes a demand.",
        "Advance tax or self-assessment tax claimed but not matched to a challan, typically from a wrong tax year or PAN on the payment.",
      ],
    },
    {
      id: "06",
      heading: "HOW TO RESPOND TO A DEMAND",
      body:
        "You have three routes, and picking the right one matters more than speed:",
      bullets: [
        "Agree and pay: if the CPC is right (a genuine missed challan, a real arithmetic slip), pay through e-Pay Tax within 30 days. Interest at 1% per month runs on unpaid demands after that.",
        "Rectify: if the demand comes from a processing error, file a rectification request under the 2025 Act's successor to Section 154 through the portal, attaching the proof (TDS certificate, challan, corrected Form 168). The CPC reprocesses and issues a fresh intimation.",
        "Respond to the outstanding demand: on the portal, formally record disagreement (full or partial) with reasons. This matters because unaddressed demands get adjusted against future refunds automatically.",
      ],
      note:
        "For TDS mismatches, fix the source first: get the deductor to correct their TDS return so Form 168 updates, then rectify. A rectification filed against an uncorrected Form 168 will simply be rejected on the same mismatch.",
    },
    {
      id: "07",
      heading: "IF THE INTIMATION SHOWS A REFUND",
      body:
        "Refunds under the new Act flow to the pre-validated bank account linked on the portal. If the intimation shows a refund but the money does not arrive within a few weeks, the usual causes are a failed bank validation (IFSC changes after bank mergers are the classic), or an adjustment of the refund against an older outstanding demand. Check Pending Actions for any refund-adjustment communication: the department must intimate before setting off a refund against past demands, and you can contest an incorrect old demand instead of silently losing the refund.",
    },
    {
      id: "08",
      heading: "WHAT A 270(1) INTIMATION IS NOT",
      body:
        "Keeping the intimation in perspective avoids both panic and complacency:",
      bullets: [
        "It is not a scrutiny notice. Selection for detailed scrutiny is a separate, human-driven process with its own notice; automated processing does not examine your documents.",
        "It is not immunity. A processed return can still be selected for scrutiny within the statutory window, or reopened later under Sections 280/281 if information surfaces.",
        "It is not optional reading. A demand inside it is a deemed demand notice under Section 289, and a proposed-adjustment communication inside the process has a hard 30-day response window.",
        "It is not always right. CPC processing works off data feeds; where the feed is wrong (deductor errors, duplicated AIS entries), the demand is wrong, and rectification exists precisely for that.",
      ],
    },
    {
      id: "09",
      heading: "TIMELINE: WHEN TO EXPECT YOURS",
      body:
        "For tax year 2026-27, returns filed by the 31 July 2027 (salaried) and 31 August 2027 (non-audit business) deadlines will mostly be processed in the weeks and months that follow, with simple refund returns often processed within days and heavier returns taking longer. The outer statutory limit for processing runs from the end of the financial year in which the return is filed, so intimations can validly arrive many months after filing. If you have not received one, check the e-filing portal under View Filed Returns rather than relying on email; the portal record is authoritative, and intimations are downloadable there.",
    },
  ],
  faqs: [
    {
      q: "I got an intimation quoting Section 270(1) instead of 143(1). Is it genuine?",
      a: "Yes, if it relates to a return filed under the Income Tax Act 2025 (tax year 2026-27 onwards). Section 270(1) is the new Act's automated processing provision, playing the role 143(1) played under the 1961 Act. Verify it on the e-filing portal under View Filed Returns; a genuine intimation appears against the relevant return with a DIN.",
    },
    {
      q: "Does Section 270(1) have anything to do with the old Section 270A penalty?",
      a: "No, and the numbering coincidence confuses many people. Section 270A of the 1961 Act was the under-reporting penalty. Section 270(1) of the 2025 Act is the routine processing intimation. A 270(1) intimation is not a penalty and not an allegation; check the Act cited on the document to know which regime you are reading.",
    },
    {
      q: "The intimation shows no demand and no refund. Do I do anything?",
      a: "No action needed. The CPC's computation matches your return. Download the PDF and keep it with that year's tax records; banks and visa processes sometimes ask for processed-return proof.",
    },
    {
      q: "I received a proposed adjustment communication. Is that the same as the intimation?",
      a: "It is the step before it. The CPC is telling you what it intends to change and giving you 30 days to object with evidence through the portal. Respond within the window; if you convince the system (a valid TDS certificate, a misread entry), the final 270(1) intimation issues without the adjustment. Silence guarantees the adjustment goes through.",
    },
    {
      q: "My demand is a TDS mismatch caused by my employer. Why is it my problem?",
      a: "Because credit is granted on what is deposited and reported against your PAN in Form 168, not on what your payslip says. Get the employer to correct their TDS return; once Form 168 updates, file a rectification and the demand drops. If the employer deducted but never deposited, you still have a right to credit on your certificate, but that requires a documented grievance rather than a routine rectification.",
    },
    {
      q: "What happens if I ignore a 270(1) demand?",
      a: "Interest accrues at 1% per month after the 30-day window, and the demand sits on your record. The department's first recovery step is silent: your next refund gets adjusted against it. Persistent demands escalate to recovery measures. Even a demand you believe is wrong should be formally disagreed with on the portal, not ignored.",
    },
    {
      q: "Can I revise my return after getting a 270(1) intimation?",
      a: "Processing does not end the revision window. For tax year 2026-27, a revised return can be filed until 31 March 2028. Use revision when the mistake is in your return (missed income, wrong figures) and rectification when the mistake is in the CPC's processing. Filing the wrong one of the two is a common and time-costly error.",
    },
    {
      q: "My FY 2025-26 return got a 143(1) and my tax year 2026-27 return got a 270(1). Is that a mistake?",
      a: "No, that is exactly how the transition works. Returns for AY 2026-27 and earlier are processed under the 1961 Act (143(1)); returns filed under the 2025 Act are processed under Section 270(1). Both documents are valid under their respective Acts and both are handled the same way in practice.",
    },
  ],
  sources: [
    {
      name: "Income Tax Act 2025 - processing and demand provisions",
      url: "https://www.incometaxindia.gov.in/income-tax-act-20251",
      description: "Section 270(1) (processing of returns) and Section 289 (intimation with amount payable deemed a notice of demand).",
    },
    {
      name: "Income Tax Act 1961, Section 143(1)",
      url: "https://incometaxindia.gov.in",
      description: "Predecessor provision, still governing returns for AY 2026-27 and earlier.",
    },
    {
      name: "Income Tax e-Filing Portal",
      url: "https://www.incometax.gov.in/iec/foportal/",
      description: "View Filed Returns, proposed-adjustment responses, rectification requests, and outstanding demand responses.",
    },
  ],
};
