// generate-invoice
// Full implementation per §22 and §10
// Internal function - called by other edge functions (razorpay-webhook, retainer-billing-webhook)
//
// Spec:
// - GST determination: CGST 9% + SGST 9% if same state as OLLVY_GST_STATE, else IGST 18%
// - Generate invoice number (INV-YYYY-NNNNN format)
// - In production: generate PDF via @react-pdf/renderer and store in /invoices/
// - For now: create invoice record with metadata (PDF generation is a separate step)

import { getSupabaseAdmin } from '../_shared/supabase-admin.ts';

export interface GenerateInvoiceInput {
  order_id?: string;
  retainer_subscription_id?: string;
}

export interface GenerateInvoiceOutput {
  ok: boolean;
  error?: string;
  invoice_id?: string;
  invoice_number?: string;
}

/**
 * generate-invoice
 *
 * Spec: CGST/SGST vs IGST from OLLVY_GST_STATE env var. PDF to /invoices/. Send push.
 */
export async function generateInvoice(
  input: GenerateInvoiceInput
): Promise<GenerateInvoiceOutput> {
  const supabase = getSupabaseAdmin();

  try {
    const { order_id, retainer_subscription_id } = input;

    // Must have either order_id or retainer_subscription_id
    if (!order_id && !retainer_subscription_id) {
      return { ok: false, error: 'Either order_id or retainer_subscription_id is required' };
    }

    let userId: string;
    let basePaisa: number;
    let gstPaisa: number;
    let govtFeesPaisa: number;
    let totalPaisa: number;
    let invoiceType: 'order' | 'retainer_cycle';
    let userState: string;

    if (order_id) {
      // Fetch order details
      const { data: order, error: orderError } = await supabase
        .from('orders')
        .select(`
          *,
          users!inner (id, state, business_name)
        `)
        .eq('id', order_id)
        .single();

      if (orderError || !order) {
        return { ok: false, error: 'Order not found' };
      }

      userId = order.user_id;
      basePaisa = order.price_base_paisa_snapshot;
      gstPaisa = order.price_gst_paisa_snapshot;
      govtFeesPaisa = order.price_govt_fees_paisa_snapshot;
      totalPaisa = order.total_paisa_snapshot;
      invoiceType = 'order';
      userState = order.users.state || '';
    } else {
      // Fetch retainer subscription details
      const { data: retainer, error: retainerError } = await supabase
        .from('retainer_subscriptions')
        .select(`
          *,
          users!inner (id, state, business_name)
        `)
        .eq('id', retainer_subscription_id)
        .single();

      if (retainerError || !retainer) {
        return { ok: false, error: 'Retainer subscription not found' };
      }

      userId = retainer.user_id;
      basePaisa = retainer.monthly_price_paisa;
      gstPaisa = Math.round(basePaisa * 0.18); // 18% GST
      govtFeesPaisa = 0;
      totalPaisa = basePaisa + gstPaisa;
      invoiceType = 'retainer_cycle';
      userState = retainer.users.state || '';
    }

    // Check if invoice already exists
    const existingQuery = order_id
      ? supabase.from('invoices').select('id').eq('order_id', order_id).single()
      : supabase.from('invoices').select('id').eq('retainer_subscription_id', retainer_subscription_id).single();

    const { data: existingInvoice } = await existingQuery;
    if (existingInvoice) {
      return { ok: true, invoice_id: existingInvoice.id, error: 'Invoice already exists' };
    }

    // Determine GST type (CGST/SGST vs IGST)
    const ollvyState = Deno.env.get('OLLVY_GST_STATE') || 'DL';
    const isSameState = userState.toLowerCase() === ollvyState.toLowerCase();

    // GST breakdown for invoice display
    const gstBreakdown = isSameState
      ? { cgst: Math.round(gstPaisa / 2), sgst: Math.round(gstPaisa / 2), igst: 0 }
      : { cgst: 0, sgst: 0, igst: gstPaisa };

    // Create invoice record
    const invoiceData: any = {
      user_id: userId,
      amount_base_paisa: basePaisa,
      amount_gst_paisa: gstPaisa,
      amount_govt_fees_paisa: govtFeesPaisa,
      amount_total_paisa: totalPaisa,
      type: invoiceType,
      issued_at: new Date().toISOString(),
      gst_type: isSameState ? 'cgst_sgst' : 'igst',
      cgst_paisa: gstBreakdown.cgst,
      sgst_paisa: gstBreakdown.sgst,
      igst_paisa: gstBreakdown.igst,
    };

    if (order_id) {
      invoiceData.order_id = order_id;
    } else {
      invoiceData.retainer_subscription_id = retainer_subscription_id;
    }

    const { data: invoice, error: invoiceError } = await supabase
      .from('invoices')
      .insert(invoiceData)
      .select()
      .single();

    if (invoiceError) {
      console.error('Failed to create invoice:', invoiceError);
      return { ok: false, error: 'Failed to create invoice' };
    }

    // Invoice number is generated by DB trigger (INV-YYYY-NNNNN format)

    // Notify user
    await supabase.from('notifications').insert({
      user_id: userId,
      type: 'invoice_generated',
      title: 'Invoice Ready',
      body: 'Your invoice has been generated and is available for download.',
    });

    console.log(`Generated invoice ${invoice.id} for ${order_id ? 'order' : 'retainer'}`);

    return {
      ok: true,
      invoice_id: invoice.id,
      invoice_number: invoice.invoice_number,
    };
  } catch (error) {
    console.error('Generate invoice error:', error);
    return { ok: false, error: error.message };
  }
}

// For direct HTTP invocation during development/testing
import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { corsHeaders } from '../_shared/cors.ts';
import { verifyCron } from '../_shared/auth.ts';

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  // For testing: require service role key
  const authResult = verifyCron(req);
  if (!authResult.success) {
    return new Response(
      JSON.stringify({ ok: false, error: 'Internal function - requires service role key' }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 401 }
    );
  }

  const body = await req.json();
  const result = await generateInvoice(body);

  return new Response(
    JSON.stringify(result),
    { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: result.ok ? 200 : 500 }
  );
});
