import { ServiceConfig } from '../services'

export const payrollManagement: ServiceConfig = {
  slug: 'payroll-management',
  name: 'Payroll Management',
  shortName: 'Payroll',
  category: 'Payroll',
  tagline: 'Salary slips. TDS. PF. ESI. All handled, every month.',

  ollvyFee: 5999,
  retainerCycleLabel: 'per month',
  govtFee: undefined,

  slaDays: 5,
  isRetainer: true,
  serviceType: 'Monthly retainer',
  mandatoryFor: 'All businesses with employees',
  legalBasis: 'Payment of Wages Act, PF Act 1952, ESI Act 1948',
  penaltyForMissing: 'PF: 1% per month + damages. ESI: 12% per annum',
  penaltyColor: 'amber',

  seoTitle: 'Payroll Services for Startups | Salary, TDS, PF, ESI | ₹2,999/mo | Ollvy',
  seoDescription:
    'Full payroll service for startups. Salary processing, TDS, PF, ESI compliance. Fixed ₹2,999/month for up to 10 employees. Dedicated payroll specialist.',
  canonicalUrl: 'https://www.ollvy.com/services/payroll-management',

  processSteps: [
    {
      step: 1,
      title: 'Share your employee data',
      timeline: 'Day 1-3',
      body: "Employee list with salary structure, PAN, Aadhaar, bank details. For existing employees, share last month's salary register. For new employees, share offer letter and joining date. A payroll specialist is assigned within 4 hours.",
      visual: 'upload',
      milestone: 'Payroll specialist assigned',
    },
    {
      step: 2,
      title: 'Salary calculated with deductions',
      timeline: 'Day 3-4',
      body: 'Gross salary, TDS, PF (employee + employer), ESI (if applicable), professional tax. All deductions calculated. Leave adjustments applied. Salary slip draft shared for your review.',
      visual: 'form',
      milestone: 'Salary calculation ready',
    },
    {
      step: 3,
      title: 'Salary disbursed + challans paid',
      timeline: 'Day 4-5',
      body: 'You approve and transfer salaries to employee accounts. We prepare PF, ESI, TDS challans. You pay the challans. PF due 15th, ESI due 15th, TDS due 7th of following month.',
      visual: 'stamp',
      milestone: 'Salaries disbursed, challans ready',
    },
    {
      step: 4,
      title: 'Salary slips generated + filed returns',
      timeline: 'Monthly',
      body: 'Salary slips generated for all employees - sent via email or app. PF return (ECR) filed on EPFO portal. ESI contribution uploaded. All proof stored in your account.',
      visual: 'calendar',
      milestone: 'Month-end payroll complete',
      isCompletion: true,
    },
  ],

  whatsIncluded: [
    {
      title: 'Full salary calculation with all deductions',
      body: 'Gross to net salary calculation: basic, HRA, special allowance, TDS, PF (12% employee + 12% employer), ESI (0.75% employee + 3.25% employer), professional tax. All components handled.',
      mockVisualType: 'receipt',
      mockVisualData: {
        row1: 'Gross Salary: ₹75,000',
        row2: 'TDS: ₹4,500 · PF: ₹9,000 · PT: ₹200',
        row3: 'Net Payable: ₹61,300',
        note: 'Salary slip for May 2025',
      },
    },
    {
      title: 'PF registration and monthly filing',
      body: 'If you have 20+ employees, PF is mandatory. We handle EPFO registration (if needed) and file monthly ECR (Electronic Challan cum Return). UAN generation for new employees included.',
      comparisonWithout: 'Navigate EPFO portal - 3+ hours/month',
      comparisonWithOllvy: 'ECR filed, challan prepared - you just pay',
    },
    {
      title: 'ESI registration and filing (if applicable)',
      body: 'ESI is mandatory for employees earning below ₹21,000/month at establishments with 10+ employees. We handle ESIC registration and monthly contribution uploads.',
      comparisonWithout: 'Miss ESI threshold - face penalty on inspection',
      comparisonWithOllvy: 'Eligibility tracked, contributions filed',
    },
    {
      title: 'TDS on salary - 24Q filing',
      body: "Salary TDS calculated based on employee's declared investments (80C, 80D, HRA). Quarterly 24Q return filed. Form 16 generated by June 15 every year.",
      mockVisualType: 'calendar',
      mockVisualData: {
        row1: 'Monthly: Salary TDS calculated',
        row2: 'Quarterly: 24Q filed',
        row3: 'Annual: Form 16 by June 15',
      },
    },
    {
      title: 'Salary slips for every employee',
      body: 'PDF salary slips with all components, deductions, and year-to-date totals. Sent to employee email on salary date. Stored in your account permanently.',
    },
  ],

  serviceRisks: [
    {
      icon: 'clock',
      title: 'PF deposit late - interest + damages',
      body: 'PF contribution due 15th of following month. Late: 1% per month interest + damages up to 100% of arrears. At ₹50,000 PF contribution, 3 months late = ₹3,500+ in interest and damages.',
    },
    {
      icon: 'document',
      title: 'Employee PAN/Aadhaar missing',
      body: 'TDS requires employee PAN. PF requires UAN (which needs Aadhaar). Missing documents delay salary processing. We collect these during onboarding.',
    },
    {
      icon: 'alert',
      title: 'Crossed 20 employees - PF now mandatory',
      body: 'PF becomes mandatory once you have 20+ employees. Many startups miss this threshold. Your 20th employee hire triggers PF registration within 30 days. We track headcount.',
    },
  ],

  profilePersonas: [
    {
      label: 'First employee hire',
      detail: 'New to payroll. We set up salary structure, explain deductions.',
    },
    {
      label: '5-10 employees',
      detail: 'Growing team. PF and TDS compliance handled monthly.',
    },
    {
      label: 'Just crossed 20 employees',
      detail: 'PF registration mandatory. We handle EPFO setup and first filing.',
    },
    {
      label: 'Have mix of contractors and employees',
      detail: 'Employees get salary slips. Contractors get 194J TDS. Both handled.',
    },
  ],

  reviewKeywordChips: [
    '✓ PF always on time',
    '✓ Form 16 ready in June',
    '✓ Salary slips professional',
    '✓ Never missed 15th',
    '✓ Fixed monthly fee',
  ],

  relatedSlugs: ['tds-monthly-compliance', 'business-itr', 'pvt-ltd-incorporation'],

  faqs: [
    {
      category: 'General',
      q: 'Do I need payroll service if I have only 2 employees?',
      a: 'Depends on your comfort level. With 2 employees, you can manage salary manually. But TDS calculation, Form 16 generation, and compliance tracking become complex. Most founders outsource at 3+ employees.',
    },
    {
      category: 'General',
      q: 'Is PF mandatory for all companies?',
      a: "PF is mandatory for establishments with 20+ employees. Below 20, it's voluntary. However, once you register for PF (even voluntarily), you cannot de-register. We advise based on your headcount plans.",
    },
    {
      category: 'Process',
      q: 'What is the pricing for more than 10 employees?',
      a: '₹2,999/month covers up to 10 employees. Above 10: +₹200 per additional employee per month. 15 employees = ₹2,999 + (5 × ₹200) = ₹3,999/month.',
    },
    {
      category: 'Process',
      q: 'How do employees get their salary slips?',
      a: "PDF salary slips sent via email on salary date. We can also integrate with your HR system if you use one. Employees can also access via the Ollvy app if they're invited.",
    },
    {
      category: 'Documents',
      q: 'What do I need to provide monthly?',
      a: 'Attendance/leave data, any salary changes (increments, bonuses), new joiners with PAN/Aadhaar/bank details, exits with last working day. We send a simple checklist on the 1st of every month.',
    },
    {
      category: 'After Completion',
      q: 'When do employees get Form 16?',
      a: 'Form 16 is due June 15 every year. We file Q4 24Q by May 31 and generate Form 16 from TRACES by June 1. Employees receive it via email before June 15.',
    },
  ],

  reviewSources: [
    {
      name: 'EPFO',
      url: 'https://www.epfindia.gov.in',
      description: 'Employees Provident Fund Organisation - PF compliance',
    },
    {
      name: 'ESIC',
      url: 'https://www.esic.in',
      description: 'Employees State Insurance Corporation - ESI compliance',
    },
    {
      name: 'TRACES',
      url: 'https://www.tdscpc.gov.in',
      description: 'TDS returns and Form 16 generation',
    },
  ],

  unlocks: [
    {
      name: 'TDS Monthly Compliance',
      explanation: 'If you also have contractor/vendor payments.',
      price: '₹1,999/month',
      type: 'beneficial',
      slug: 'tds-monthly-compliance',
    },
    {
      name: 'Business ITR',
      explanation: 'Annual ITR filing with salary expenses.',
      price: '₹11,999',
      type: 'required',
      slug: 'business-itr',
    },
  ],

  showCompletionStats: false,
  showApprovalRate: false,
}
